<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

/**
 * REAL public locations across the Kimberley region of Western Australia
 * (Broome, Cable Beach, Derby, Kununurra, El Questro, Purnululu / Bungle
 * Bungles), sourced from the Google Places API (New) Text Search.
 *
 * Idempotent: upserts by `name` so re-running is safe. We set tier explicitly
 * and let points = defaultPointsForTier(tier); the Location model's saving()
 * hook re-derives tier from points so the two stay consistent. updateOrCreate
 * runs save(), so that hook fires.
 */
class WaBulkKimberleySeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            [
                'slug' => 'wa_kim_mirima_national_park',
                'name' => 'Mirima National Park',
                'category' => 'parks',
                'latitude' => -15.7712391,
                'longitude' => 128.7513459,
                'address' => 'Hidden Valley Rd, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Mirima National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_bandilngan_windjana_gorge_national_park',
                'name' => 'Bandilngan (Windjana Gorge) National Park',
                'category' => 'parks',
                'latitude' => -17.412684,
                'longitude' => 124.942986,
                'address' => 'Fairfield-Leopold Downs Rd, Wunaamin Miliwundi Ranges WA 6728, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Bandilngan (Windjana Gorge) National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_mitchell_river_national_park',
                'name' => 'Mitchell River National Park',
                'category' => 'parks',
                'latitude' => -14.9420379,
                'longitude' => 125.6821933,
                'address' => 'Unnamed Road, Mitchell Plateau WA 6740, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Mitchell River National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_purnululu_national_park',
                'name' => 'Purnululu National Park',
                'category' => 'parks',
                'latitude' => -17.4934098,
                'longitude' => 128.3809441,
                'address' => 'Western Australia 6770, Australia',
                'tier' => 6,
                'is_major_destination' => true,
                'description' => 'Purnululu National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_danggu_gorge_national_park',
                'name' => 'Danggu Gorge National Park',
                'category' => 'parks',
                'latitude' => -18.10653,
                'longitude' => 125.6996202,
                'address' => 'Leopold Downs Rd, Wunaamin Miliwundi Ranges WA 6728, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Danggu Gorge National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_prince_regent_national_park',
                'name' => 'Prince Regent National Park',
                'category' => 'parks',
                'latitude' => -15.5529295,
                'longitude' => 125.3979493,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Prince Regent National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_dimalurru_tunnel_creek_national_park',
                'name' => 'Dimalurru (Tunnel Creek) National Park',
                'category' => 'parks',
                'latitude' => -17.6095718,
                'longitude' => 125.1453292,
                'address' => 'Leopold Downs Rd, Wunaamin Miliwundi Ranges WA 6728, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Dimalurru (Tunnel Creek) National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_lawley_river_national_park',
                'name' => 'Lawley River National Park',
                'category' => 'parks',
                'latitude' => -14.6878524,
                'longitude' => 125.8934136,
                'address' => 'Mitchell Plateau WA 6740, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lawley River National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_cathedral_gorge',
                'name' => 'Cathedral Gorge',
                'category' => 'parks',
                'latitude' => -17.4804966,
                'longitude' => 128.3727006,
                'address' => 'Purnululu National Park, Purnululu WA 6770, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Cathedral Gorge — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_drysdale_river_national_park',
                'name' => 'Drysdale River National Park',
                'category' => 'parks',
                'latitude' => -14.9510915,
                'longitude' => 126.986828,
                'address' => 'Drysdale River WA 6740, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Drysdale River National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_bell_gorge',
                'name' => 'Bell Gorge',
                'category' => 'parks',
                'latitude' => -16.9916464,
                'longitude' => 125.2031899,
                'address' => 'Silent Grove Rd, Wunaamin Miliwundi Ranges WA 6728, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Bell Gorge — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_king_george_falls_kimberley_western_australia',
                'name' => 'King George Falls - Kimberley, Western Australia',
                'category' => 'parks',
                'latitude' => -14.0417554,
                'longitude' => 127.3219299,
                'address' => 'Oombulgurri WA 6740, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'King George Falls - Kimberley, Western Australia — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_little_mertens_falls',
                'name' => 'Little Mertens Falls',
                'category' => 'parks',
                'latitude' => -14.8227666,
                'longitude' => 125.7107981,
                'address' => 'Mitchell Plateau WA 6740, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Little Mertens Falls — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_galvans_gorge',
                'name' => 'Galvans Gorge',
                'category' => 'parks',
                'latitude' => -16.8013674,
                'longitude' => 125.8444076,
                'address' => 'Wunaamin Miliwundi Ranges WA 6728, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Galvans Gorge — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_the_bungle_bungles',
                'name' => 'The Bungle Bungles',
                'category' => 'scenic',
                'latitude' => -17.4891658,
                'longitude' => 128.3702558,
                'address' => 'Purnululu WA 6770, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'The Bungle Bungles — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_manning_gorge',
                'name' => 'Manning Gorge',
                'category' => 'parks',
                'latitude' => -16.6379556,
                'longitude' => 125.9148849,
                'address' => 'Derby-Gibb River Rd, Derby WA 6728, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Manning Gorge — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_keep_river_national_park',
                'name' => 'Keep River National Park',
                'category' => 'parks',
                'latitude' => -15.5899639,
                'longitude' => 129.4035876,
                'address' => 'Baines NT 0852, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Keep River National Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_emma_gorge',
                'name' => 'Emma Gorge',
                'category' => 'parks',
                'latitude' => -15.893987,
                'longitude' => 128.13388,
                'address' => 'Unnamed Road, Durack WA 6743, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Emma Gorge — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_revolver_falls',
                'name' => 'Revolver Falls',
                'category' => 'parks',
                'latitude' => -16.2061917,
                'longitude' => 128.53947,
                'address' => 'Lake Argyle WA 6743, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Revolver Falls — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_black_rock_falls',
                'name' => 'Black Rock Falls',
                'category' => 'parks',
                'latitude' => -15.6263597,
                'longitude' => 128.6713359,
                'address' => 'Lake Argyle WA 6743, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Black Rock Falls — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_echidna_chasm',
                'name' => 'Echidna Chasm',
                'category' => 'scenic',
                'latitude' => -17.3287269,
                'longitude' => 128.4155118,
                'address' => 'Purnululu WA 6770, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Echidna Chasm — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_kelly_s_knob_thegoowiyeng',
                'name' => 'Kelly\'s Knob / Thegoowiyeng',
                'category' => 'scenic',
                'latitude' => -15.7648906,
                'longitude' => 128.7426039,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Kelly\'s Knob / Thegoowiyeng — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_tunnel_creek_walk',
                'name' => 'Tunnel Creek Walk',
                'category' => 'scenic',
                'latitude' => -17.6065063,
                'longitude' => 125.1456909,
                'address' => 'Parking lot, Leopold Downs Rd, Wunaamin Miliwundi Ranges WA 6728, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Tunnel Creek Walk — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_kings_cascade',
                'name' => 'Kings Cascade',
                'category' => 'scenic',
                'latitude' => -15.622536,
                'longitude' => 125.304945,
                'address' => 'Prince Regent River WA 6740, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Kings Cascade — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_wolfe_creek_crater',
                'name' => 'Wolfe Creek Crater',
                'category' => 'parks',
                'latitude' => -19.172972,
                'longitude' => 127.7981498,
                'address' => 'Sturt Creek WA 6770, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Wolfe Creek Crater — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_front_beach',
                'name' => 'Front Beach',
                'category' => 'scenic',
                'latitude' => -16.1489125,
                'longitude' => 123.7822364,
                'address' => 'Front Beach, Western Australia 6728, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Front Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_cable_beach',
                'name' => 'Cable Beach',
                'category' => 'scenic',
                'latitude' => -17.9542995,
                'longitude' => 122.2040847,
                'address' => 'Cable Beach Rd W, Cable Beach WA 6726, Australia',
                'tier' => 4,
                'is_major_destination' => true,
                'description' => 'Cable Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_reddell_beach',
                'name' => 'Reddell Beach',
                'category' => 'scenic',
                'latitude' => -17.9899571,
                'longitude' => 122.1933177,
                'address' => 'Riddell Beach, Minyirr WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Reddell Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_riddell_beach',
                'name' => 'Riddell Beach',
                'category' => 'scenic',
                'latitude' => -17.9899571,
                'longitude' => 122.1933177,
                'address' => 'Riddell Beach, Minyirr WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Riddell Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_pandanus_beach',
                'name' => 'Pandanus Beach',
                'category' => 'scenic',
                'latitude' => -15.7916667,
                'longitude' => 128.6986111,
                'address' => 'Pandanus Beach, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Pandanus Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_yumurryumuh_beach',
                'name' => 'Yumurryumuh Beach',
                'category' => 'scenic',
                'latitude' => -16.1717871,
                'longitude' => 123.5748145,
                'address' => 'Yumurryumuh Beach, Western Australia 6728, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Yumurryumuh Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_gantheaume_point',
                'name' => 'Gantheaume Point',
                'category' => 'scenic',
                'latitude' => -17.9738748,
                'longitude' => 122.1774568,
                'address' => 'Gantheaume Point Rd, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Gantheaume Point — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_quondong_beach',
                'name' => 'Quondong Beach',
                'category' => 'scenic',
                'latitude' => -17.580385,
                'longitude' => 122.1571309,
                'address' => 'Quondong Beach, Waterbank WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Quondong Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_coolibah_beach',
                'name' => 'Coolibah Beach',
                'category' => 'scenic',
                'latitude' => -15.7928038,
                'longitude' => 128.7028381,
                'address' => 'Coolibah Beach, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Coolibah Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_martins_beach',
                'name' => 'Martins Beach',
                'category' => 'scenic',
                'latitude' => -15.7880556,
                'longitude' => 128.6922222,
                'address' => 'Martins Beach, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Martins Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_town_beach',
                'name' => 'Town Beach',
                'category' => 'scenic',
                'latitude' => -17.9692132,
                'longitude' => 122.2368073,
                'address' => '90 Robinson St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Town Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_rigby_beach',
                'name' => 'Rigby Beach',
                'category' => 'scenic',
                'latitude' => -15.7944444,
                'longitude' => 128.7277778,
                'address' => 'Rigby Beach, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Rigby Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_bandicoot_beach',
                'name' => 'Bandicoot Beach',
                'category' => 'scenic',
                'latitude' => -15.7872222,
                'longitude' => 128.6913889,
                'address' => 'Bandicoot Beach, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Bandicoot Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_olivers_beach',
                'name' => 'Olivers Beach',
                'category' => 'scenic',
                'latitude' => -15.8088889,
                'longitude' => 128.7413889,
                'address' => 'Olivers Beach, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Olivers Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_five_rivers_lookout',
                'name' => 'Five Rivers Lookout',
                'category' => 'scenic',
                'latitude' => -15.4506559,
                'longitude' => 128.1192169,
                'address' => 'Hugo Austla Dr, Wyndham WA 6740, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Five Rivers Lookout — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_kabbarli_lookout',
                'name' => 'Kabbarli Lookout',
                'category' => 'scenic',
                'latitude' => -18.0082682,
                'longitude' => 122.2092932,
                'address' => 'Kabbarli Rd, Minyirr WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Kabbarli Lookout — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_kungkalanayi_lookout',
                'name' => 'Kungkalanayi Lookout',
                'category' => 'scenic',
                'latitude' => -17.4163268,
                'longitude' => 128.306133,
                'address' => 'Ord River WA 6770, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Kungkalanayi Lookout — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_branco_s_lookout',
                'name' => 'Branco\'s Lookout',
                'category' => 'scenic',
                'latitude' => -15.9794256,
                'longitude' => 127.9076805,
                'address' => 'Unnamed Road, Durack WA 6743, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Branco\'s Lookout — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_roebuck_bay_lookout',
                'name' => 'Roebuck Bay Lookout',
                'category' => 'scenic',
                'latitude' => -17.9569468,
                'longitude' => 122.2441374,
                'address' => '45C Dampier Terrace, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Roebuck Bay Lookout — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_saddleback_ridge_and_lookout',
                'name' => 'Saddleback Ridge and Lookout',
                'category' => 'scenic',
                'latitude' => -15.9942706,
                'longitude' => 127.9799937,
                'address' => 'Durack WA 6743, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Saddleback Ridge and Lookout — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_cockburn_ranges_lookout',
                'name' => 'Cockburn Ranges Lookout',
                'category' => 'scenic',
                'latitude' => -15.7461512,
                'longitude' => 127.8256348,
                'address' => 'Durack WA 6743, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Cockburn Ranges Lookout — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_piccaninny_creek_lookout',
                'name' => 'Piccaninny Creek Lookout',
                'category' => 'scenic',
                'latitude' => -17.48789,
                'longitude' => 128.383353,
                'address' => 'G96M+R8, Purnululu WA 6770, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Piccaninny Creek Lookout — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_halls_creek_lookout',
                'name' => 'Halls Creek Lookout',
                'category' => 'scenic',
                'latitude' => -18.2070409,
                'longitude' => 127.6443881,
                'address' => 'Unnamed Road, Halls Creek WA 6770, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Halls Creek Lookout — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_broome_historical_museum',
                'name' => 'Broome Historical Museum',
                'category' => 'scenic',
                'latitude' => -17.9679419,
                'longitude' => 122.2365837,
                'address' => 'Town Beach Reserve, 67 Robinson St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Broome Historical Museum — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_streeter_s_jetty_broome',
                'name' => 'Streeter\'s Jetty Broome',
                'category' => 'scenic',
                'latitude' => -17.9533537,
                'longitude' => 122.2456592,
                'address' => '9 Dampier Terrace, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Streeter\'s Jetty Broome — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_town_beach_jetty',
                'name' => 'Town Beach Jetty',
                'category' => 'scenic',
                'latitude' => -17.971222,
                'longitude' => 122.2378578,
                'address' => '26GQ+XP, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Town Beach Jetty — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_roebuck_bay',
                'name' => 'Roebuck Bay',
                'category' => 'scenic',
                'latitude' => -17.9654059,
                'longitude' => 122.2380978,
                'address' => 'Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Roebuck Bay — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_johnny_chi_lane',
                'name' => 'Johnny Chi Lane',
                'category' => 'scenic',
                'latitude' => -17.9540932,
                'longitude' => 122.2445336,
                'address' => '22 Dampier Terrace, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Johnny Chi Lane — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_9_zeros_9_stories',
                'name' => '9 Zeros 9 Stories',
                'category' => 'scenic',
                'latitude' => -17.9701926,
                'longitude' => 122.2367791,
                'address' => 'Robinson St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => '9 Zeros 9 Stories — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_three_pearling_legends',
                'name' => 'Three Pearling Legends',
                'category' => 'scenic',
                'latitude' => -17.955627,
                'longitude' => 122.244062,
                'address' => '36 Dampier Terrace, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Three Pearling Legends — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_start_of_the_pearling_story',
                'name' => 'Start of the Pearling Story',
                'category' => 'scenic',
                'latitude' => -17.95329,
                'longitude' => 122.244905,
                'address' => '11 Dampier Terrace, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Start of the Pearling Story — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_coastalpeninsular',
                'name' => 'coastalpeninsular',
                'category' => 'scenic',
                'latitude' => -17.9682917,
                'longitude' => 122.2281917,
                'address' => '2/17 Raible Rd, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'coastalpeninsular — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_the_pearling_timeline',
                'name' => 'The Pearling Timeline',
                'category' => 'scenic',
                'latitude' => -17.953431,
                'longitude' => 122.244849,
                'address' => '3b/15 Dampier Terrace, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'The Pearling Timeline — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_broome_port_jetty',
                'name' => 'Broome Port Jetty',
                'category' => 'scenic',
                'latitude' => -18.0036062,
                'longitude' => 122.2110876,
                'address' => '401 Port Dr, Minyirr WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Broome Port Jetty — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_public_art_chinatown_traders',
                'name' => 'Public Art - Chinatown Traders',
                'category' => 'scenic',
                'latitude' => -17.953965,
                'longitude' => 122.24354,
                'address' => '1/23 Carnarvon St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Public Art - Chinatown Traders — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_sam_male_sculpture',
                'name' => 'Sam Male Sculpture',
                'category' => 'scenic',
                'latitude' => -17.95317,
                'longitude' => 122.244419,
                'address' => 'Paspaley Pearls, 2 Short St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Sam Male Sculpture — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_simpson_beach',
                'name' => 'Simpson Beach',
                'category' => 'scenic',
                'latitude' => -17.9994403,
                'longitude' => 122.2069955,
                'address' => '401 Port Dr, Minyirr WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Simpson Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_demco_nagulan_julan_beach',
                'name' => 'Demco (Nagulan Julan) Beach',
                'category' => 'scenic',
                'latitude' => -17.9738924,
                'longitude' => 122.2286863,
                'address' => '21 Demco Dr, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Demco (Nagulan Julan) Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_japanese_pillars',
                'name' => 'Japanese Pillars',
                'category' => 'scenic',
                'latitude' => -17.95564,
                'longitude' => 122.243938,
                'address' => 'Shop 3/2 Napier Terrace, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Japanese Pillars — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_multilingual_street_signs',
                'name' => 'Multilingual Street Signs',
                'category' => 'scenic',
                'latitude' => -17.953002,
                'longitude' => 122.243435,
                'address' => '15/17 Carnarvon St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Multilingual Street Signs — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_broome_courthouse_markets',
                'name' => 'Broome Courthouse Markets',
                'category' => 'scenic',
                'latitude' => -17.9568861,
                'longitude' => 122.2403472,
                'address' => '8 Hamersley St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Broome Courthouse Markets — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_fusion_interwoven_culture',
                'name' => 'Fusion: Interwoven Culture',
                'category' => 'scenic',
                'latitude' => -17.955284,
                'longitude' => 122.242941,
                'address' => '40 Napier Terrace, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Fusion: Interwoven Culture — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_broome_bird_observatory',
                'name' => 'Broome Bird Observatory',
                'category' => 'scenic',
                'latitude' => -17.9751158,
                'longitude' => 122.3449459,
                'address' => 'Crab Creek Road, Roebuck WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Broome Bird Observatory — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_dinosaur_footprints_at_gantheaume_point',
                'name' => 'Dinosaur footprints at Gantheaume Point',
                'category' => 'scenic',
                'latitude' => -17.9739348,
                'longitude' => 122.17669,
                'address' => '502 Gantheaume Point Rd, Minyirr WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Dinosaur footprints at Gantheaume Point — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_broome_mangrove',
                'name' => 'Broome Mangrove',
                'category' => 'parks',
                'latitude' => -17.9662915,
                'longitude' => 122.2387576,
                'address' => 'Catalinas I Apartments, 39 Hamersley St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Broome Mangrove — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_gantheaume_beach',
                'name' => 'Gantheaume Beach',
                'category' => 'scenic',
                'latitude' => -17.9723393,
                'longitude' => 122.1888927,
                'address' => 'Lurujarri Walk, Cable Beach WA 6726, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Gantheaume Beach — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_dampier_creek',
                'name' => 'Dampier Creek',
                'category' => 'scenic',
                'latitude' => -17.9471995,
                'longitude' => 122.2509593,
                'address' => '29 Dunnart Crescent, Djugun WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Dampier Creek — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_chinatown_broome',
                'name' => 'Chinatown Broome',
                'category' => 'scenic',
                'latitude' => -17.9537635,
                'longitude' => 122.2432323,
                'address' => 'Carnarvon St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Chinatown Broome — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_cable_beach_foreshore',
                'name' => 'Cable Beach Foreshore',
                'category' => 'parks',
                'latitude' => -17.9282747,
                'longitude' => 122.2105974,
                'address' => 'Cable Beach Rd W, Cable Beach WA 6726, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Cable Beach Foreshore — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_our_lady_queen_of_peace_cathedral',
                'name' => 'Our Lady Queen of Peace Cathedral',
                'category' => 'scenic',
                'latitude' => -17.9600003,
                'longitude' => 122.238615,
                'address' => '34 Weld St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Our Lady Queen of Peace Cathedral — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_bedford_park',
                'name' => 'Bedford Park',
                'category' => 'parks',
                'latitude' => -17.9629466,
                'longitude' => 122.2389772,
                'address' => 'Anne St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Bedford Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_red_sun_camels',
                'name' => 'Red Sun Camels',
                'category' => 'scenic',
                'latitude' => -17.92672,
                'longitude' => 122.210112,
                'address' => 'Cable Beach WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Red Sun Camels — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_sun_pictures',
                'name' => 'Sun Pictures',
                'category' => 'scenic',
                'latitude' => -17.9534721,
                'longitude' => 122.2431789,
                'address' => '8 Carnarvon St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Sun Pictures — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_broome_dinosaur_experience',
                'name' => 'Broome Dinosaur Experience',
                'category' => 'scenic',
                'latitude' => -17.9533672,
                'longitude' => 122.241535,
                'address' => '1 Hamersley St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Broome Dinosaur Experience — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_ivanhoe_crossing',
                'name' => 'Ivanhoe Crossing',
                'category' => 'scenic',
                'latitude' => -15.6895199,
                'longitude' => 128.6881697,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Ivanhoe Crossing — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_ord_river_kununurra_western_australia',
                'name' => 'Ord River,Kununurra, Western Australia',
                'category' => 'scenic',
                'latitude' => -15.7783483,
                'longitude' => 128.7439001,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Ord River,Kununurra, Western Australia — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_kununurra_museum_run_by_the_kununurra_historical_society_inc',
                'name' => 'Kununurra Museum (run by the Kununurra Historical Society Inc)',
                'category' => 'scenic',
                'latitude' => -15.77539,
                'longitude' => 128.73733,
                'address' => '72 Coolibah Dr, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Kununurra Museum (run by the Kununurra Historical Society Inc) — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_celebrity_tree_park',
                'name' => 'Celebrity Tree Park',
                'category' => 'parks',
                'latitude' => -15.7844022,
                'longitude' => 128.737146,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Celebrity Tree Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_swim_beach_park',
                'name' => 'Swim Beach Park',
                'category' => 'parks',
                'latitude' => -15.7922553,
                'longitude' => 128.6993423,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Swim Beach Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_mayiba_middle_springs',
                'name' => 'Mayiba (Middle springs)',
                'category' => 'scenic',
                'latitude' => -15.6337655,
                'longitude' => 128.6696548,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Mayiba (Middle springs) — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_mirima_rocks',
                'name' => 'Mirima Rocks',
                'category' => 'scenic',
                'latitude' => -15.7637141,
                'longitude' => 128.7517579,
                'address' => 'Hidden Valley Rd, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Mirima Rocks — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_thethebeleng_elephant_rock_kununurra_wa',
                'name' => 'Thethebeleng / Elephant Rock, Kununurra WA',
                'category' => 'scenic',
                'latitude' => -15.826015,
                'longitude' => 128.7504818,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Thethebeleng / Elephant Rock, Kununurra WA — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_waringarri_aboriginal_arts',
                'name' => 'Waringarri Aboriginal Arts',
                'category' => 'scenic',
                'latitude' => -15.761855,
                'longitude' => 128.737315,
                'address' => '16 Speargrass Rd, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Waringarri Aboriginal Arts — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_kangaroo_haven',
                'name' => 'Kangaroo Haven',
                'category' => 'parks',
                'latitude' => -15.822381,
                'longitude' => 128.774504,
                'address' => '90 Egret Cl, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Kangaroo Haven — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_lion_s_park',
                'name' => 'Lion\'s Park',
                'category' => 'parks',
                'latitude' => -15.7908378,
                'longitude' => 128.6918033,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Lion\'s Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_valentine_springs',
                'name' => 'Valentine Springs',
                'category' => 'scenic',
                'latitude' => -15.7178506,
                'longitude' => 128.6495734,
                'address' => 'Valentine Spring Rd, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Valentine Springs — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_anzac_hill',
                'name' => 'ANZAC Hill',
                'category' => 'parks',
                'latitude' => -15.781802,
                'longitude' => 128.6788076,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'ANZAC Hill — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_artopia_gallery',
                'name' => 'Artopia Gallery',
                'category' => 'scenic',
                'latitude' => -15.7739678,
                'longitude' => 128.7393652,
                'address' => '116 Coolibah Dr, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Artopia Gallery — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_mirima_lookout',
                'name' => 'Mirima Lookout',
                'category' => 'parks',
                'latitude' => -15.7627754,
                'longitude' => 128.750014,
                'address' => '16 Poincettia Way, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Mirima Lookout — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_kununurra_arboretum',
                'name' => 'Kununurra Arboretum',
                'category' => 'parks',
                'latitude' => -15.7777714,
                'longitude' => 128.7296184,
                'address' => '75 Ivanhoe Rd, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Kununurra Arboretum — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_kununurra_diversion_dam',
                'name' => 'Kununurra Diversion Dam',
                'category' => 'scenic',
                'latitude' => -15.7917816,
                'longitude' => 128.6954198,
                'address' => 'Victoria Hwy, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Kununurra Diversion Dam — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_goomig_conservation_park',
                'name' => 'Goomig Conservation Park',
                'category' => 'parks',
                'latitude' => -15.5727779,
                'longitude' => 128.8414602,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Goomig Conservation Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_white_gum_park',
                'name' => 'White Gum Park',
                'category' => 'parks',
                'latitude' => -15.7716891,
                'longitude' => 128.7397641,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'White Gum Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_big_boab_tree',
                'name' => 'Big Boab Tree',
                'category' => 'parks',
                'latitude' => -15.7787866,
                'longitude' => 128.742622,
                'address' => 'Victoria Hwy, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Big Boab Tree — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_kununurra_cenotaph',
                'name' => 'Kununurra cenotaph',
                'category' => 'parks',
                'latitude' => -15.7734545,
                'longitude' => 128.739011,
                'address' => '115 Coolibah Dr, Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Kununurra cenotaph — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_point_spring_nature_reserve',
                'name' => 'Point Spring Nature Reserve',
                'category' => 'parks',
                'latitude' => -15.4030337,
                'longitude' => 128.8884938,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Point Spring Nature Reserve — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_secret_springs_turnoff',
                'name' => 'Secret Springs Turnoff',
                'category' => 'scenic',
                'latitude' => -15.609195,
                'longitude' => 128.6549638,
                'address' => 'Lake Argyle WA 6743, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Secret Springs Turnoff — a striking Kimberley landmark of red rock, turquoise water and endless horizon in Australia\'s untamed far north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kim_jemarnde_wooningim_conservation_park',
                'name' => 'Jemarnde-wooningim Conservation Park',
                'category' => 'parks',
                'latitude' => -15.3400656,
                'longitude' => 128.8414602,
                'address' => 'Kununurra WA 6743, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Jemarnde-wooningim Conservation Park — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_lake_rason',
                'name' => 'Lake Rason',
                'category' => 'parks',
                'latitude' => -16.752291,
                'longitude' => 127.0054739,
                'address' => 'Lake Rason, Durack WA 6743, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lake Rason — a wild Kimberley landscape of gorges, waterholes and ancient country, rewarding those who venture into Australia\'s remote north-west.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_kim_haven_broome',
                'name' => 'Haven Broome',
                'category' => 'food',
                'latitude' => -17.9525557,
                'longitude' => 122.243453,
                'address' => 'Shop 17/8 Short St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Haven Broome — a welcome Kimberley pit-stop for a feed and a cold drink amid the red dirt and big-sky country.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_kim_zookeepers_broome',
                'name' => 'Zookeepers Broome',
                'category' => 'food',
                'latitude' => -17.9314201,
                'longitude' => 122.2146741,
                'address' => '2 Challenor Dr, Cable Beach WA 6726, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Zookeepers Broome — a welcome Kimberley pit-stop for a feed and a cold drink amid the red dirt and big-sky country.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_kim_cable_beach_house',
                'name' => 'Cable Beach House',
                'category' => 'food',
                'latitude' => -17.9299046,
                'longitude' => 122.2103017,
                'address' => 'Cable Beach Rd W, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Cable Beach House — a welcome Kimberley pit-stop for a feed and a cold drink amid the red dirt and big-sky country.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_kim_the_millie_cafe',
                'name' => 'The Millie cafe',
                'category' => 'food',
                'latitude' => -17.9277421,
                'longitude' => 122.2136967,
                'address' => '8 Millington Rd, Cable Beach WA 6726, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'The Millie cafe — a welcome Kimberley pit-stop for a feed and a cold drink amid the red dirt and big-sky country.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_kim_chi_mayi_kitchen',
                'name' => 'Chi Mayi Kitchen',
                'category' => 'food',
                'latitude' => -17.9541374,
                'longitude' => 122.2441113,
                'address' => 'Johnny Chi Lane, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Chi Mayi Kitchen — a welcome Kimberley pit-stop for a feed and a cold drink amid the red dirt and big-sky country.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_kim_papa_fuego',
                'name' => 'Papa Fuego',
                'category' => 'food',
                'latitude' => -17.9635181,
                'longitude' => 122.2374267,
                'address' => '2 Louis St, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Papa Fuego — a welcome Kimberley pit-stop for a feed and a cold drink amid the red dirt and big-sky country.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_kim_bali_hai_cafe_restaurant',
                'name' => 'Bali Hai Cafe & Restaurant',
                'category' => 'food',
                'latitude' => -17.9352524,
                'longitude' => 122.2157442,
                'address' => '6 Murray Rd, Cable Beach WA 6726, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Bali Hai Cafe & Restaurant — a welcome Kimberley pit-stop for a feed and a cold drink amid the red dirt and big-sky country.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_kim_sale_co_speciality_coffee',
                'name' => 'Sale & Co Speciality Coffee',
                'category' => 'food',
                'latitude' => -17.9590112,
                'longitude' => 122.2220293,
                'address' => '1 Port Dr, Broome WA 6725, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Sale & Co Speciality Coffee — a welcome Kimberley pit-stop for a feed and a cold drink amid the red dirt and big-sky country.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
        ];

        foreach ($locations as $data) {
            // points drives tier via the model's saving() hook; use the per-tier
            // default so the explicit tier and the derived tier agree.
            $data['points'] = Location::defaultPointsForTier($data['tier']);

            Location::updateOrCreate(
                ['name' => $data['name']],
                array_merge($data, [
                    'verification_tags' => [],
                    'active' => true,
                    'status' => Location::STATUS_APPROVED,
                    'submitted_by' => null,
                ])
            );
        }
    }
}
