<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

/**
 * REAL public locations across the WA Wheatbelt (Wave Rock/Hyden, York,
 * Northam, Wongan Hills and surrounding granite-rock country), sourced from
 * the Google Places API (New) Text Search. Idempotent: upserts by `name`.
 *
 * tier is set explicitly here; points is set to defaultPointsForTier(tier)
 * and the Location model's saving() hook re-derives tier from points, so the
 * explicit tier and the derived tier stay consistent. updateOrCreate runs
 * save() so that hook fires.
 */
class WaBulkWheatbeltSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            [
                'name' => 'Quairading Community Nature Reserve',
                'slug' => 'wb_quairading_community_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.0220299,
                'longitude' => 117.3723107,
                'address' => 'Quairading-York Rd, Quairading WA 6383, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Quairading Community Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Kokerbin Nature Reserve',
                'slug' => 'wb_kokerbin_nature_reserve',
                'category' => 'parks',
                'latitude' => -31.8881393,
                'longitude' => 117.7050807,
                'address' => 'Kwolyin WA 6385, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Kokerbin Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Kokerbin Rock',
                'slug' => 'wb_kokerbin_rock',
                'category' => 'scenic',
                'latitude' => -31.8877716,
                'longitude' => 117.7059163,
                'address' => '4P64+V9, Kwolyin WA 6385, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Kokerbin Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Kokerbin Rock Picnic Area',
                'slug' => 'wb_kokerbin_rock_picnic_area',
                'category' => 'scenic',
                'latitude' => -31.886994,
                'longitude' => 117.7094087,
                'address' => 'Kwolyin WA 6385, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Kokerbin Rock Picnic Area is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Coarin Rock',
                'slug' => 'wb_coarin_rock',
                'category' => 'scenic',
                'latitude' => -31.9364867,
                'longitude' => 117.7534648,
                'address' => 'Kwolyin WA 6385, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Coarin Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Quajabin Peak',
                'slug' => 'wb_quajabin_peak',
                'category' => 'scenic',
                'latitude' => -32.2166667,
                'longitude' => 117.1833333,
                'address' => 'Quajabin Peak, Bally Bally WA 6304, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Quajabin Peak is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Kellerberrin',
                'slug' => 'wb_kellerberrin',
                'category' => 'scenic',
                'latitude' => -31.6326508,
                'longitude' => 117.7192968,
                'address' => 'Kellerberrin WA 6410, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Kellerberrin is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Kellerberrin Genestreaming Journey Sculpture',
                'slug' => 'wb_kellerberrin_genestreaming_journey_sculpture',
                'category' => 'scenic',
                'latitude' => -31.6328529,
                'longitude' => 117.7197983,
                'address' => 'Kellerberrin WA 6410, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Kellerberrin Genestreaming Journey Sculpture is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Kellerberrin Pink Bridge',
                'slug' => 'wb_kellerberrin_pink_bridge',
                'category' => 'scenic',
                'latitude' => -31.6328774,
                'longitude' => 117.7217936,
                'address' => '110 Massingham St, Kellerberrin WA 6410, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Kellerberrin Pink Bridge is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Kellerberrin Hill Lookout',
                'slug' => 'wb_kellerberrin_hill_lookout',
                'category' => 'scenic',
                'latitude' => -31.6233448,
                'longitude' => 117.7092439,
                'address' => 'Kellerberrin Hill Rd, Kellerberrin WA 6410, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Kellerberrin Hill Lookout is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Pig Rock',
                'slug' => 'wb_pig_rock',
                'category' => 'scenic',
                'latitude' => -31.6237184,
                'longitude' => 117.7100117,
                'address' => '9PG6+G2, Kellerberrin WA 6410, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Pig Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Shark\'s Mouth Rock',
                'slug' => 'wb_shark_s_mouth_rock',
                'category' => 'scenic',
                'latitude' => -31.596078,
                'longitude' => 117.7673717,
                'address' => 'Kellerberrin WA 6410, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Shark\'s Mouth Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Corrigin Nature Reserve',
                'slug' => 'wb_corrigin_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.3459628,
                'longitude' => 117.841063,
                'address' => 'Corrigin WA 6375, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Corrigin Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Qualering Rock',
                'slug' => 'wb_qualering_rock',
                'category' => 'scenic',
                'latitude' => -31.4833333,
                'longitude' => 117.4,
                'address' => 'Qualering Rock, North Tammin WA 6409, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Qualering Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Bulgin Rock',
                'slug' => 'wb_bulgin_rock',
                'category' => 'scenic',
                'latitude' => -31.6563195,
                'longitude' => 117.0873228,
                'address' => 'Bulgin Rd, Meckering WA 6405, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Bulgin Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Yorkrakine Rock and Nature Reserve',
                'slug' => 'wb_yorkrakine_rock_and_nature_reserve',
                'category' => 'parks',
                'latitude' => -31.4218425,
                'longitude' => 117.5173234,
                'address' => 'Tammin-Wyalkatchem Rd, North Tammin WA 6409, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Yorkrakine Rock and Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Kulbullikin Rock',
                'slug' => 'wb_kulbullikin_rock',
                'category' => 'scenic',
                'latitude' => -31.8666667,
                'longitude' => 118.0666667,
                'address' => 'Kulbullikin Rock, Bruce Rock WA 6418, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Kulbullikin Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Pioneer Park',
                'slug' => 'wb_pioneer_park',
                'category' => 'parks',
                'latitude' => -32.3682634,
                'longitude' => 117.0100617,
                'address' => '83 Brookton Hwy, Brookton WA 6306, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Pioneer Park rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'name' => 'Brookton Lookout',
                'slug' => 'wb_brookton_lookout',
                'category' => 'scenic',
                'latitude' => -32.3699101,
                'longitude' => 116.9850417,
                'address' => 'Unnamed Road, Brookton WA 6306, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Brookton Lookout is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Bruce Rock Cafe- Love that food',
                'slug' => 'wb_bruce_rock_cafe_love_that_food',
                'category' => 'food',
                'latitude' => -31.8783493,
                'longitude' => 118.1486053,
                'address' => '48 Johnson St, Bruce Rock WA 6418, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A welcoming country stop in the heart of the Wheatbelt — fuel up on local fare before exploring the surrounding wheat-and-sheep country.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Bruce Rock Community Resource Centre (Inc)',
                'slug' => 'wb_bruce_rock_community_resource_centre_inc',
                'category' => 'scenic',
                'latitude' => -31.8781533,
                'longitude' => 118.148688,
                'address' => '40/42 Johnson St, Bruce Rock WA 6418, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Bruce Rock Community Resource Centre (Inc) is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Bruce Rock Museum',
                'slug' => 'wb_bruce_rock_museum',
                'category' => 'scenic',
                'latitude' => -31.87648,
                'longitude' => 118.14841,
                'address' => '24 Johnson St, Bruce Rock WA 6418, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Bruce Rock Museum is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'name' => 'Bruce Rock Pioneer Well',
                'slug' => 'wb_bruce_rock_pioneer_well',
                'category' => 'scenic',
                'latitude' => -31.8685696,
                'longitude' => 118.1669575,
                'address' => 'Bruce Rock WA 6418, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Bruce Rock Pioneer Well is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Mt Brown – Picnic & BBQ Area',
                'slug' => 'wb_mt_brown_picnic_bbq_area',
                'category' => 'scenic',
                'latitude' => -31.8860353,
                'longitude' => 116.7860503,
                'address' => 'Pioneer Dr, York WA 6302, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Mt Brown – Picnic & BBQ Area is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Mount Brown Lookout',
                'slug' => 'wb_mount_brown_lookout',
                'category' => 'scenic',
                'latitude' => -31.8875814,
                'longitude' => 116.7849623,
                'address' => 'York WA 6302, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Mount Brown Lookout is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'York Suspension Bridge',
                'slug' => 'wb_york_suspension_bridge',
                'category' => 'scenic',
                'latitude' => -31.8867533,
                'longitude' => 116.7703973,
                'address' => 'Christie Retreat, York WA 6302, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. York Suspension Bridge is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Avon Walk Trail',
                'slug' => 'wb_avon_walk_trail',
                'category' => 'parks',
                'latitude' => -31.8866471,
                'longitude' => 116.7703567,
                'address' => '14 Lowe St, York WA 6302, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Avon Walk Trail rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Avon Park',
                'slug' => 'wb_avon_park',
                'category' => 'parks',
                'latitude' => -31.8879844,
                'longitude' => 116.7699067,
                'address' => 'Lowe St, York WA 6302, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Avon Park rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'name' => 'Gather York',
                'slug' => 'wb_gather_york',
                'category' => 'scenic',
                'latitude' => -31.8940414,
                'longitude' => 116.7664665,
                'address' => '10 Henrietta St, York WA 6302, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Gather York is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'The Old York Mill',
                'slug' => 'wb_the_old_york_mill',
                'category' => 'scenic',
                'latitude' => -31.8940406,
                'longitude' => 116.7661724,
                'address' => '10 Henrietta St, York WA 6302, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. The Old York Mill is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Culbarting Rock',
                'slug' => 'wb_culbarting_rock',
                'category' => 'scenic',
                'latitude' => -31.4,
                'longitude' => 117.0166667,
                'address' => 'Culbarting Rock, Ucarty WA 6462, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Culbarting Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Hindmarsh Nature Reserve',
                'slug' => 'wb_hindmarsh_nature_reserve',
                'category' => 'parks',
                'latitude' => -31.3130947,
                'longitude' => 117.1338285,
                'address' => 'Hindmarsh WA 6462, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Hindmarsh Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Korbrelkulling Rock',
                'slug' => 'wb_korbrelkulling_rock',
                'category' => 'scenic',
                'latitude' => -31.6,
                'longitude' => 118.1833333,
                'address' => 'Korbrelkulling Rock, Nangeenan WA 6414, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Korbrelkulling Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Bentenalling Rock',
                'slug' => 'wb_bentenalling_rock',
                'category' => 'scenic',
                'latitude' => -31.5666667,
                'longitude' => 116.8333333,
                'address' => 'Bentenalling Rock, Southern Brook WA 6401, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Bentenalling Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Claypit Nature Reserve',
                'slug' => 'wb_claypit_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.7955872,
                'longitude' => 117.4336137,
                'address' => 'Wickepin WA 6370, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Claypit Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Commodine Nature Reserve',
                'slug' => 'wb_commodine_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.7803388,
                'longitude' => 117.3102271,
                'address' => 'Commodine WA 6311, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Commodine Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Yornaning Dam',
                'slug' => 'wb_yornaning_dam',
                'category' => 'scenic',
                'latitude' => -32.7396594,
                'longitude' => 117.15933,
                'address' => 'Yornaning WA 6311, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Yornaning Dam is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Totadgin Rock',
                'slug' => 'wb_totadgin_rock',
                'category' => 'scenic',
                'latitude' => -31.5746141,
                'longitude' => 118.2120512,
                'address' => 'Nangeenan WA 6414, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Totadgin Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Totadgin Conservation Park',
                'slug' => 'wb_totadgin_conservation_park',
                'category' => 'parks',
                'latitude' => -31.5730542,
                'longitude' => 118.2146501,
                'address' => 'Nangeenan WA 6414, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Totadgin Conservation Park rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Statues Lake',
                'slug' => 'wb_statues_lake',
                'category' => 'parks',
                'latitude' => -32.4534706,
                'longitude' => 118.2036042,
                'address' => 'Kondinin WA 6367, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Statues Lake rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Kondinin Lake Nature Reserve',
                'slug' => 'wb_kondinin_lake_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.4905826,
                'longitude' => 118.2117257,
                'address' => 'Kondinin WA 6367, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Kondinin Lake Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Merredin Nature Reserve',
                'slug' => 'wb_merredin_nature_reserve',
                'category' => 'parks',
                'latitude' => -31.5268942,
                'longitude' => 118.2321952,
                'address' => 'Merredin WA 6415, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Merredin Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Fitzgerald Street Northam',
                'slug' => 'wb_fitzgerald_street_northam',
                'category' => 'scenic',
                'latitude' => -31.6544714,
                'longitude' => 116.671912,
                'address' => '171 Fitzgerald St E, Northam WA 6401, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Fitzgerald Street Northam is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Bernard Park',
                'slug' => 'wb_bernard_park',
                'category' => 'parks',
                'latitude' => -31.6510073,
                'longitude' => 116.6720754,
                'address' => '2 Grey St, Northam WA 6401, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Bernard Park rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'name' => 'Back 2 The Grind',
                'slug' => 'wb_back_2_the_grind',
                'category' => 'scenic',
                'latitude' => -31.6517792,
                'longitude' => 116.671707,
                'address' => 'Northam WA 6401, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Back 2 The Grind is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Avon Descent Start Tower',
                'slug' => 'wb_avon_descent_start_tower',
                'category' => 'scenic',
                'latitude' => -31.6518759,
                'longitude' => 116.6714382,
                'address' => '2 Grey St, Northam WA 6401, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Avon Descent Start Tower is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Bilya Koort Boodja Centre for Nyoongar Culture and Environmental Knowledge',
                'slug' => 'wb_bilya_koort_boodja_centre_for_nyoongar_culture_and_environmental_knowledge',
                'category' => 'scenic',
                'latitude' => -31.6526987,
                'longitude' => 116.6710697,
                'address' => '2 Grey St, Northam WA 6401, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Bilya Koort Boodja Centre for Nyoongar Culture and Environmental Knowledge is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Karenbrenin Rock',
                'slug' => 'wb_karenbrenin_rock',
                'category' => 'scenic',
                'latitude' => -31.8333333,
                'longitude' => 118.3833333,
                'address' => 'Karenbrenin Rock, Cramphorne WA 6420, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Karenbrenin Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Northam Suspension Bridge',
                'slug' => 'wb_northam_suspension_bridge',
                'category' => 'scenic',
                'latitude' => -31.6521252,
                'longitude' => 116.6705478,
                'address' => 'Northam WA 6401, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Northam Suspension Bridge is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Mount Ommanney Lookout',
                'slug' => 'wb_mount_ommanney_lookout',
                'category' => 'scenic',
                'latitude' => -31.6562698,
                'longitude' => 116.6523793,
                'address' => 'Mount Ommanney Rd, Northam WA 6401, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Mount Ommanney Lookout is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Tin Dog Creek',
                'slug' => 'wb_tin_dog_creek',
                'category' => 'scenic',
                'latitude' => -31.1984293,
                'longitude' => 117.0278468,
                'address' => 'Dowerin WA 6461, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Tin Dog Creek is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Merredin Railway Dam',
                'slug' => 'wb_merredin_railway_dam',
                'category' => 'scenic',
                'latitude' => -31.4771482,
                'longitude' => 118.2909909,
                'address' => 'Benson Rd, Merredin WA 6415, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Merredin Railway Dam is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Bendering Nature Reserve',
                'slug' => 'wb_bendering_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.3778525,
                'longitude' => 118.3754131,
                'address' => 'Kondinin WA 6367, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Bendering Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Merredin Peak',
                'slug' => 'wb_merredin_peak',
                'category' => 'scenic',
                'latitude' => -31.4678973,
                'longitude' => 118.2928285,
                'address' => 'Benson Rd, Merredin WA 6415, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Merredin Peak is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Mackie Park',
                'slug' => 'wb_mackie_park',
                'category' => 'parks',
                'latitude' => -32.9345975,
                'longitude' => 117.1790429,
                'address' => 'Narrogin WA 6312, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Mackie Park rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'name' => 'Yeerakine Rock',
                'slug' => 'wb_yeerakine_rock',
                'category' => 'scenic',
                'latitude' => -32.5608013,
                'longitude' => 118.315636,
                'address' => 'Kondinin WA 6367, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Yeerakine Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Lions Park',
                'slug' => 'wb_lions_park',
                'category' => 'parks',
                'latitude' => -32.939476,
                'longitude' => 117.178201,
                'address' => '6312/138 Federal St, Narrogin WA 6312, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Lions Park rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'name' => 'Foxes Lair',
                'slug' => 'wb_foxes_lair',
                'category' => 'parks',
                'latitude' => -32.9420368,
                'longitude' => 117.1606739,
                'address' => 'Narrogin WA 6312, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Foxes Lair rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Kondinin Salt Marsh Nature Reserve',
                'slug' => 'wb_kondinin_salt_marsh_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.5782601,
                'longitude' => 118.3637264,
                'address' => 'Jilakin WA 6365, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Kondinin Salt Marsh Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Jilakin Rock City',
                'slug' => 'wb_jilakin_rock_city',
                'category' => 'scenic',
                'latitude' => -32.6609928,
                'longitude' => 118.3279742,
                'address' => 'Kulin WA 6365, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Jilakin Rock City is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'North Karlgarin Nature Reserve',
                'slug' => 'wb_north_karlgarin_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.3842177,
                'longitude' => 118.4980744,
                'address' => 'Kondinin WA 6367, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. North Karlgarin Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Eaglestone Rock',
                'slug' => 'wb_eaglestone_rock',
                'category' => 'scenic',
                'latitude' => -31.0833217,
                'longitude' => 118.2417836,
                'address' => 'Nungarin WA 6490, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Eaglestone Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Gabby Quoi Quoi Lookout',
                'slug' => 'wb_gabby_quoi_quoi_lookout',
                'category' => 'scenic',
                'latitude' => -31.0543474,
                'longitude' => 116.7881102,
                'address' => 'Gabbyquoiquoi Rd, Konnongorring WA 6603, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Gabby Quoi Quoi Lookout is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Roe Nature Reserve',
                'slug' => 'wb_roe_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.3286798,
                'longitude' => 118.7023068,
                'address' => 'Karlgarin WA 6358, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Roe Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Giant Ram Park',
                'slug' => 'wb_giant_ram_park',
                'category' => 'parks',
                'latitude' => -33.3104077,
                'longitude' => 117.3376848,
                'address' => '39 Scaddan St, Wagin WA 6315, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Giant Ram Park rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Puntapin Rock',
                'slug' => 'wb_puntapin_rock',
                'category' => 'scenic',
                'latitude' => -33.3241097,
                'longitude' => 117.398293,
                'address' => 'Puntaping Rd, Wagin WA 6315, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Puntapin Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Newcarlbeon Rock',
                'slug' => 'wb_newcarlbeon_rock',
                'category' => 'scenic',
                'latitude' => -30.6678574,
                'longitude' => 117.4208573,
                'address' => 'Newcarlbeon WA 6475, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Newcarlbeon Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Parkeyerring Nature Reserve',
                'slug' => 'wb_parkeyerring_nature_reserve',
                'category' => 'parks',
                'latitude' => -33.3745268,
                'longitude' => 117.3440192,
                'address' => 'Lime Lake WA 6315, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Parkeyerring Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Buckley\'s Breakaway',
                'slug' => 'wb_buckley_s_breakaway',
                'category' => 'scenic',
                'latitude' => -32.6488129,
                'longitude' => 118.745402,
                'address' => 'Karlgarin Rd S, Pingaring WA 6357, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Buckley\'s Breakaway is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'The Lace Place',
                'slug' => 'wb_the_lace_place',
                'category' => 'scenic',
                'latitude' => -32.4405035,
                'longitude' => 118.8970104,
                'address' => 'Wave Rock Rd, Hyden WA 6359, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. The Lace Place is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Wave Rock',
                'slug' => 'wb_wave_rock',
                'category' => 'scenic',
                'latitude' => -32.4437886,
                'longitude' => 118.8972421,
                'address' => 'Hyden WA 6359, Australia',
                'tier' => 4,
                'is_major_destination' => true,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Wave Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Lake Magic Swimming Pond',
                'slug' => 'wb_lake_magic_swimming_pond',
                'category' => 'parks',
                'latitude' => -32.433876,
                'longitude' => 118.906929,
                'address' => 'Wave Rock Rd, Hyden WA 6359, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Lake Magic Swimming Pond rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Wongan Hills Nature Reserve',
                'slug' => 'wb_wongan_hills_nature_reserve',
                'category' => 'parks',
                'latitude' => -30.8051709,
                'longitude' => 116.6346995,
                'address' => 'Wongan Hills WA 6603, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Wongan Hills Nature Reserve rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Coomelberrup Rock',
                'slug' => 'wb_coomelberrup_rock',
                'category' => 'scenic',
                'latitude' => -33.45,
                'longitude' => 117.7833333,
                'address' => 'Coomelberrup Rock, Datatine WA 6317, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Coomelberrup Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Mulka\'s Cave and Gnamma Walk Trail',
                'slug' => 'wb_mulka_s_cave_and_gnamma_walk_trail',
                'category' => 'scenic',
                'latitude' => -32.3150156,
                'longitude' => 118.961632,
                'address' => 'Bates Rd, Hyden WA 6359, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Mulka\'s Cave and Gnamma Walk Trail is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Chiddarcooping Nature Reserve Sign',
                'slug' => 'wb_chiddarcooping_nature_reserve_sign',
                'category' => 'parks',
                'latitude' => -30.8875967,
                'longitude' => 118.6530062,
                'address' => 'Morrison Rd, Warralakin WA 6421, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A peaceful Wheatbelt reserve of bushland, granite outcrops and wildflowers, alive with birdlife and quiet walk trails. Chiddarcooping Nature Reserve Sign rewards those who venture inland.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Graham Rock',
                'slug' => 'wb_graham_rock',
                'category' => 'scenic',
                'latitude' => -32.5,
                'longitude' => 119.0333333,
                'address' => 'Graham Rock, Hyden WA 6359, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Graham Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'King Rock',
                'slug' => 'wb_king_rock',
                'category' => 'scenic',
                'latitude' => -32.3165913,
                'longitude' => 119.1517902,
                'address' => 'N King Rocks Rd, Hyden WA 6359, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. King Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Baladjie rock',
                'slug' => 'wb_baladjie_rock',
                'category' => 'scenic',
                'latitude' => -30.9534221,
                'longitude' => 118.877647,
                'address' => 'Boodarockin WA 6423, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Baladjie rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Beringbooding Rock',
                'slug' => 'wb_beringbooding_rock',
                'category' => 'scenic',
                'latitude' => -30.5593503,
                'longitude' => 118.4939151,
                'address' => '1487 Cunderin Rd, Bonnie Rock WA 6479, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Beringbooding Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Elachbutting Rock',
                'slug' => 'wb_elachbutting_rock',
                'category' => 'scenic',
                'latitude' => -30.5924159,
                'longitude' => 118.6092702,
                'address' => '2157 Elachbutting Rd, Elachbutting WA 6479, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Elachbutting Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Geeraning Rock granite monolith',
                'slug' => 'wb_geeraning_rock_granite_monolith',
                'category' => 'scenic',
                'latitude' => -30.5265924,
                'longitude' => 118.5997114,
                'address' => 'Elachbutting WA 6479, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Geeraning Rock granite monolith is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Marble Rock',
                'slug' => 'wb_marble_rock',
                'category' => 'scenic',
                'latitude' => -32.5166667,
                'longitude' => 119.4,
                'address' => 'Marble Rock, Hyden WA 6359, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Marble Rock is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Wattle Rocks',
                'slug' => 'wb_wattle_rocks',
                'category' => 'scenic',
                'latitude' => -32.2666667,
                'longitude' => 119.4666667,
                'address' => 'Wattle Rocks, Forrestania WA 6359, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A classic Wheatbelt landmark amid sweeping golden farmland and ancient granite country. Wattle Rocks is well worth the inland detour off the tourist trail.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
        ];

        foreach ($locations as $data) {
            $data['points'] = Location::defaultPointsForTier($data['tier']);

            Location::updateOrCreate(
                ['name' => $data['name']],
                array_merge($data, [
                    'verification_tags' => [],
                    'active' => true,
                    'status' => Location::STATUS_APPROVED,
                    'submitted_by' => null,
                ])
            );
        }
    }
}
