<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class WaBulkGascoyneSeeder extends Seeder
{
    /**
     * Bulk set of REAL public Gascoyne (WA) locations — Carnarvon, Shark Bay,
     * Monkey Mia, Coral Bay and surrounds — sourced from the Google Places API
     * (New) Text Search and deduplicated by Places id within the region.
     *
     * Idempotent: keyed on `name` via updateOrCreate so re-running is safe.
     * points drives tier via the Location model's saving() hook, so we set
     * points = defaultPointsForTier(tier) and let the hook re-derive tier
     * (the two agree). updateOrCreate runs save() so the hook fires.
     */
    public function run(): void
    {
        $locations = [
            [
                'slug' => 'wa_gas_6701_waterfront_cafe',
                'name' => '6701 Waterfront Cafe',
                'category' => 'food',
                'latitude' => -24.884088799999997,
                'longitude' => 113.6546731,
                'address' => '71 Olivia Terrace, Carnarvon WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => '6701 Waterfront Cafe — a welcoming Gascoyne stop to refuel with a coffee or a bite between the region\'s coast and outback.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_gas_big_lagoon_campground',
                'name' => 'Big Lagoon Campground',
                'category' => 'scenic',
                'latitude' => -25.7778419,
                'longitude' => 113.4777664,
                'address' => 'Unnamed Road, Francois Peron Nat\'l Park WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Big Lagoon Campground — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_bill_s_bay',
                'name' => 'Bill\'s Bay',
                'category' => 'scenic',
                'latitude' => -23.1424321,
                'longitude' => 113.76921739999999,
                'address' => 'Coral Bay WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Bill\'s Bay — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_bladder_inlet',
                'name' => 'Bladder Inlet',
                'category' => 'scenic',
                'latitude' => -25.880464,
                'longitude' => 113.7322883,
                'address' => '4P9J+RW, Monkey Mia WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Bladder Inlet — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_blue_lagoon_inlet',
                'name' => 'Blue Lagoon Inlet',
                'category' => 'scenic',
                'latitude' => -25.906066,
                'longitude' => 113.52788699999999,
                'address' => 'Stella Rowley Dr, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Blue Lagoon Inlet — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_blue_lagoon_pearl_farm',
                'name' => 'Blue Lagoon Pearl Farm',
                'category' => 'scenic',
                'latitude' => -25.778592999999997,
                'longitude' => 113.69159649999999,
                'address' => 'Shark Bay WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Blue Lagoon Pearl Farm — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_bundegi_beach',
                'name' => 'Bundegi Beach',
                'category' => 'scenic',
                'latitude' => -21.8265229,
                'longitude' => 114.1777657,
                'address' => 'Learmonth Minilya Rd, North West Cape WA 6707, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Bundegi Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_camp_14_mile_beach',
                'name' => 'Camp 14 Mile Beach',
                'category' => 'scenic',
                'latitude' => -23.281469299999998,
                'longitude' => 113.79032129999999,
                'address' => 'Mauds Lndng-Warroora Rd, Lyndon WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Camp 14 Mile Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_cape_peron',
                'name' => 'Cape Peron',
                'category' => 'scenic',
                'latitude' => -25.505662899999997,
                'longitude' => 113.508759,
                'address' => 'Francois Peron Nat\'l Park WA 6537, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Cape Peron — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_cape_range_national_park',
                'name' => 'Cape Range National Park',
                'category' => 'parks',
                'latitude' => -22.070994499999998,
                'longitude' => 113.97742889999999,
                'address' => 'Yardie Creek Rd, Cape Range National Park WA 6707, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Cape Range National Park — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_carnarvon_big_banana',
                'name' => 'Carnarvon Big Banana',
                'category' => 'scenic',
                'latitude' => -24.8659732,
                'longitude' => 113.68789539999999,
                'address' => '451 Robinson St, East Carnarvon WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Carnarvon Big Banana — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_carnarvon_space_and_technology_museum',
                'name' => 'Carnarvon Space and Technology Museum',
                'category' => 'scenic',
                'latitude' => -24.869345600000003,
                'longitude' => 113.70417409999999,
                'address' => 'Mahony Ave, Brown Range WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Carnarvon Space and Technology Museum — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_carnarvon_town_centre',
                'name' => 'Carnarvon Town Centre',
                'category' => 'scenic',
                'latitude' => -24.883882,
                'longitude' => 113.65668190000001,
                'address' => '1 Camel Ln, Carnarvon WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Carnarvon Town Centre — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_carnarvon_visitor_centre',
                'name' => 'Carnarvon Visitor Centre',
                'category' => 'scenic',
                'latitude' => -24.8841432,
                'longitude' => 113.6565471,
                'address' => '21 Robinson St, Carnarvon WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Carnarvon Visitor Centre — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_carnarvon_war_memorial',
                'name' => 'Carnarvon war memorial',
                'category' => 'scenic',
                'latitude' => -24.8842332,
                'longitude' => 113.65745790000001,
                'address' => '2 Stuart St, Carnarvon WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Carnarvon war memorial — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_carnavon_fascine',
                'name' => 'Carnavon Fascine',
                'category' => 'scenic',
                'latitude' => -24.884977199999998,
                'longitude' => 113.6552241,
                'address' => '81A Olivia Terrace, Carnarvon WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Carnavon Fascine — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_chair_beach',
                'name' => 'Chair beach',
                'category' => 'scenic',
                'latitude' => -25.9155338,
                'longitude' => 113.51883679999999,
                'address' => '3GM9+QG, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Chair beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_charles_knife_canyon',
                'name' => 'Charles Knife Canyon',
                'category' => 'scenic',
                'latitude' => -22.108723599999998,
                'longitude' => 114.0285079,
                'address' => 'Charles Knife Rd, Learmonth WA 6707, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Charles Knife Canyon — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_coral_bay',
                'name' => 'Coral Bay',
                'category' => 'scenic',
                'latitude' => -23.1422976,
                'longitude' => 113.77231119999999,
                'address' => 'Coral Bay WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Coral Bay — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_coral_bay_hill',
                'name' => 'Coral Bay Hill',
                'category' => 'scenic',
                'latitude' => -23.141693999999998,
                'longitude' => 113.77508089999999,
                'address' => '46 Robinson St, Coral Bay WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Coral Bay Hill — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_coral_bay_house',
                'name' => 'Coral Bay House',
                'category' => 'scenic',
                'latitude' => -23.141109399999998,
                'longitude' => 113.77273269999999,
                'address' => '2 Marlin Ct, Coral Bay WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Coral Bay House — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_coral_bay_lookout',
                'name' => 'Coral Bay Lookout',
                'category' => 'scenic',
                'latitude' => -23.1433884,
                'longitude' => 113.7674564,
                'address' => 'Coral Bay WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Coral Bay Lookout — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_coral_coast_tourist_park',
                'name' => 'Coral Coast Tourist Park',
                'category' => 'scenic',
                'latitude' => -24.879496,
                'longitude' => 113.661517,
                'address' => '108 Robinson St, Carnarvon WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Coral Coast Tourist Park — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_cuppa_crumb_cafe',
                'name' => 'Cuppa & Crumb Cafe',
                'category' => 'food',
                'latitude' => -24.883487799999997,
                'longitude' => 113.6576468,
                'address' => 'Shop C/36 Robinson St, Carnarvon WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Cuppa & Crumb Cafe — a welcoming Gascoyne stop to refuel with a coffee or a bite between the region\'s coast and outback.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_gas_denham_discovery_trail_map',
                'name' => 'Denham Discovery Trail Map',
                'category' => 'scenic',
                'latitude' => -25.9280442,
                'longitude' => 113.5349511,
                'address' => '53 Knight Terrace, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Denham Discovery Trail Map — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_denham_lookout',
                'name' => 'Denham Lookout',
                'category' => 'scenic',
                'latitude' => -25.9188217,
                'longitude' => 113.5177485,
                'address' => '3GJ9+F3, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Denham Lookout — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_denham_lookout_path',
                'name' => 'Denham lookout path',
                'category' => 'scenic',
                'latitude' => -25.9178869,
                'longitude' => 113.5211109,
                'address' => '3GJC+RC, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Denham lookout path — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_denham_playgrounds',
                'name' => 'Denham Playgrounds',
                'category' => 'scenic',
                'latitude' => -25.928684099999998,
                'longitude' => 113.53503699999999,
                'address' => '70 Knight Terrace, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Denham Playgrounds — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_denham_recreation_jetty',
                'name' => 'Denham Recreation Jetty',
                'category' => 'scenic',
                'latitude' => -25.9286253,
                'longitude' => 113.5340087,
                'address' => 'Shark Bay WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Denham Recreation Jetty — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_denham_swimming_area',
                'name' => 'Denham Swimming area',
                'category' => 'scenic',
                'latitude' => -25.9286045,
                'longitude' => 113.53430739999999,
                'address' => '70 Knight Terrace, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Denham Swimming area — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_dirk_hartog_island_national_park',
                'name' => 'Dirk Hartog Island National Park',
                'category' => 'parks',
                'latitude' => -25.8024022,
                'longitude' => 113.0250269,
                'address' => 'Dirk Hartog Island WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Dirk Hartog Island National Park — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_drapers_gorge',
                'name' => 'Drapers Gorge',
                'category' => 'parks',
                'latitude' => -24.6697906,
                'longitude' => 115.17145,
                'address' => 'Kennedy Range WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Drapers Gorge — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_eagle_bluff_lookout',
                'name' => 'Eagle Bluff Lookout',
                'category' => 'scenic',
                'latitude' => -26.0920795,
                'longitude' => 113.58070560000002,
                'address' => 'Francois Peron National Park, Francois Peron Nat\'l Park WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Eagle Bluff Lookout — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_elles_beach',
                'name' => 'Elles Beach',
                'category' => 'scenic',
                'latitude' => -23.4362583,
                'longitude' => 113.78217269999999,
                'address' => 'Lyndon WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Elles Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_emu_rising',
                'name' => 'Emu Rising',
                'category' => 'scenic',
                'latitude' => -25.926137299999997,
                'longitude' => 113.5299105,
                'address' => 'Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Emu Rising — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_fascine_caf_6701',
                'name' => 'Fascine Café 6701',
                'category' => 'food',
                'latitude' => -24.8842476,
                'longitude' => 113.65713699999999,
                'address' => '26 Robinson St, Carnarvon WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Fascine Café 6701 — a welcoming Gascoyne stop to refuel with a coffee or a bite between the region\'s coast and outback.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_gas_five_fingers_reef',
                'name' => 'Five Fingers Reef',
                'category' => 'scenic',
                'latitude' => -23.1797459,
                'longitude' => 113.7657069,
                'address' => 'Unnamed Road, Lyndon WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Five Fingers Reef — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_francois_peron_national_park',
                'name' => 'Francois Peron National Park',
                'category' => 'parks',
                'latitude' => -25.866452600000002,
                'longitude' => 113.59107979999999,
                'address' => 'Francois Peron Nat\'l Park WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Francois Peron National Park — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_freycinet_double_islands_etc_nature_reserve',
                'name' => 'Freycinet, Double Islands Etc Nature Reserve',
                'category' => 'parks',
                'latitude' => -26.512205299999998,
                'longitude' => 113.7550622,
                'address' => 'Shark Bay WA 6537, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Freycinet, Double Islands Etc Nature Reserve — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_gascoyne_bakery_cafe',
                'name' => 'Gascoyne Bakery Cafe',
                'category' => 'food',
                'latitude' => -24.8846536,
                'longitude' => 113.65671809999999,
                'address' => '12 Robinson St, Carnarvon WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Gascoyne Bakery Cafe — a welcoming Gascoyne stop to refuel with a coffee or a bite between the region\'s coast and outback.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_gas_gascoyne_growers_market',
                'name' => 'Gascoyne Growers\' Market',
                'category' => 'scenic',
                'latitude' => -24.883959299999997,
                'longitude' => 113.6561548,
                'address' => '21 Robinson St, Carnarvon WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Gascoyne Growers\' Market — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_gladstone_scenic_lookout',
                'name' => 'Gladstone Scenic Lookout',
                'category' => 'scenic',
                'latitude' => -25.985661,
                'longitude' => 114.29819239999999,
                'address' => 'Wooramel WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Gladstone Scenic Lookout — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_gudrun',
                'name' => 'Gudrun',
                'category' => 'scenic',
                'latitude' => -25.9284289,
                'longitude' => 113.53421829999999,
                'address' => 'Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Gudrun — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_honeycomb_gorge',
                'name' => 'Honeycomb Gorge',
                'category' => 'parks',
                'latitude' => -24.6467225,
                'longitude' => 115.17553499999998,
                'address' => 'West Lyons River WA 6705, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Honeycomb Gorge — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_inlet_lookout',
                'name' => 'Inlet Lookout',
                'category' => 'scenic',
                'latitude' => -25.9065732,
                'longitude' => 113.5266178,
                'address' => 'Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Inlet Lookout — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_jardilunji_mia_caf',
                'name' => 'Jardilunji Mia Cafè',
                'category' => 'food',
                'latitude' => -24.876952799999998,
                'longitude' => 113.66296419999999,
                'address' => '146 Robinson St, Carnarvon WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Jardilunji Mia Cafè — a welcoming Gascoyne stop to refuel with a coffee or a bite between the region\'s coast and outback.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_gas_kalbarri_skywalk',
                'name' => 'Kalbarri Skywalk',
                'category' => 'scenic',
                'latitude' => -27.554840600000002,
                'longitude' => 114.43397089999999,
                'address' => 'West Loop Lookout Road, Kalbarri National Park WA 6536, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Kalbarri Skywalk — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_kennedy_range_national_park',
                'name' => 'Kennedy Range National Park',
                'category' => 'parks',
                'latitude' => -24.660720599999998,
                'longitude' => 115.1828601,
                'address' => 'Lyons River Rd, Kennedy Range WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Kennedy Range National Park — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_kestrel_cafe',
                'name' => 'Kestrel Cafe',
                'category' => 'food',
                'latitude' => -24.875521,
                'longitude' => 113.63008230000001,
                'address' => '1 Annear Pl, Babbage Island WA 6701, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Kestrel Cafe — a welcoming Gascoyne stop to refuel with a coffee or a bite between the region\'s coast and outback.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_gas_lagoon',
                'name' => 'Lagoon',
                'category' => 'scenic',
                'latitude' => -23.5414601,
                'longitude' => 113.7378792,
                'address' => 'Lyndon WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lagoon — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_lagoon_creek',
                'name' => 'Lagoon Creek',
                'category' => 'scenic',
                'latitude' => -25.9060559,
                'longitude' => 113.5249279,
                'address' => '3GVF+HX, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lagoon Creek — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_lake_keene',
                'name' => 'Lake Keene',
                'category' => 'parks',
                'latitude' => -24.9487006,
                'longitude' => 115.144634,
                'address' => 'Lake Keene, Gascoyne River WA 6705, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lake Keene — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_lake_newell',
                'name' => 'Lake Newell',
                'category' => 'parks',
                'latitude' => -24.994549,
                'longitude' => 114.95502409999999,
                'address' => 'Lake Newell, Gascoyne River WA 6705, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lake Newell — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_little_lagoon',
                'name' => 'Little Lagoon',
                'category' => 'scenic',
                'latitude' => -25.8989589,
                'longitude' => 113.538021,
                'address' => 'Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Little Lagoon — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_little_lagoon_creek_lookout',
                'name' => 'Little Lagoon Creek Lookout',
                'category' => 'scenic',
                'latitude' => -25.906441400000002,
                'longitude' => 113.5267094,
                'address' => 'Stella Rowley Dr, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Little Lagoon Creek Lookout — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_luke_camping',
                'name' => 'Luke camping',
                'category' => 'scenic',
                'latitude' => -24.8646335,
                'longitude' => 113.6855487,
                'address' => '78 Shallcross St, East Carnarvon WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Luke camping — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_mauds_landing_beach',
                'name' => 'Mauds Landing Beach',
                'category' => 'scenic',
                'latitude' => -23.114622,
                'longitude' => 113.775117,
                'address' => 'Mauds Landing-Warroora Rd, Lyndon WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Mauds Landing Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_mauritius_beach',
                'name' => 'Mauritius Beach',
                'category' => 'scenic',
                'latitude' => -21.8092316,
                'longitude' => 114.09511339999999,
                'address' => 'Yardie Creek Rd, Exmouth WA 6707, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Mauritius Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_miaboolya_beach',
                'name' => 'Miaboolya Beach',
                'category' => 'scenic',
                'latitude' => -24.7939334,
                'longitude' => 113.6351078,
                'address' => 'Inggarda WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Miaboolya Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_monkey_mia',
                'name' => 'Monkey Mia',
                'category' => 'scenic',
                'latitude' => -25.794087299999997,
                'longitude' => 113.7198713,
                'address' => 'Monkey Mia WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => true,
                'description' => 'Monkey Mia — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_monkey_mia_conservation_park_visitor_centre',
                'name' => 'Monkey Mia Conservation Park Visitor Centre',
                'category' => 'parks',
                'latitude' => -25.793514899999998,
                'longitude' => 113.7197372,
                'address' => 'Monkey Mia Visitor Center, 1 Monkey Mia Rd, Monkey Mia WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Monkey Mia Conservation Park Visitor Centre — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_monkey_mia_jetty',
                'name' => 'Monkey Mia Jetty',
                'category' => 'scenic',
                'latitude' => -25.7926353,
                'longitude' => 113.72000340000001,
                'address' => 'Wulyibidi Yaninyina Walking Trail, Western Australia 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Monkey Mia Jetty — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_monkey_mia_reserve',
                'name' => 'Monkey Mia Reserve',
                'category' => 'parks',
                'latitude' => -25.801223099999998,
                'longitude' => 113.706755,
                'address' => 'Monkey Mia WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Monkey Mia Reserve — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_monkey_mia_wild_dolphin_feeding',
                'name' => 'Monkey Mia Wild Dolphin feeding',
                'category' => 'scenic',
                'latitude' => -25.793141199999997,
                'longitude' => 113.71956689999999,
                'address' => '1 Monkey Mia Rd, Monkey Mia WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Monkey Mia Wild Dolphin feeding — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_mystery_beach',
                'name' => 'Mystery Beach',
                'category' => 'scenic',
                'latitude' => -25.645916099999997,
                'longitude' => 112.9366924,
                'address' => 'Mystery Beach, Dirk Hartog Island WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Mystery Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_nature_s_window',
                'name' => 'Nature\'s Window',
                'category' => 'parks',
                'latitude' => -27.553136499999997,
                'longitude' => 114.44599269999999,
                'address' => 'Kalbarri National Park WA 6536, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Nature\'s Window — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_netta_s_beach',
                'name' => 'Netta\'s Beach',
                'category' => 'scenic',
                'latitude' => -25.932570499999997,
                'longitude' => 113.5442222,
                'address' => 'Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Netta\'s Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_ningaloo_coral_bay_bayview',
                'name' => 'Ningaloo Coral Bay - Bayview',
                'category' => 'scenic',
                'latitude' => -23.1428503,
                'longitude' => 113.7735994,
                'address' => 'Robinson St, Coral Bay WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Ningaloo Coral Bay - Bayview — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_ningaloo_coral_bay_boats',
                'name' => 'Ningaloo Coral Bay Boats',
                'category' => 'scenic',
                'latitude' => -23.1425141,
                'longitude' => 113.7727511,
                'address' => 'Robinson St, Coral Bay WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Ningaloo Coral Bay Boats — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_ningaloo_roast',
                'name' => 'Ningaloo Roast',
                'category' => 'scenic',
                'latitude' => -24.8840836,
                'longitude' => 113.6546631,
                'address' => '71 Olivia Terrace, Carnarvon WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Ningaloo Roast — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_old_prawn_jetty',
                'name' => 'Old Prawn Jetty',
                'category' => 'scenic',
                'latitude' => -24.8829291,
                'longitude' => 113.6313122,
                'address' => 'Binning Rd, Babbage Island WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Old Prawn Jetty — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_on_the_deck_shark_bay',
                'name' => 'On the Deck @ Shark Bay',
                'category' => 'scenic',
                'latitude' => -25.918976699999998,
                'longitude' => 113.5284047,
                'address' => '6 Oxenham Chase, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'On the Deck @ Shark Bay — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_one_mile_jetty_museum',
                'name' => 'One Mile Jetty Museum',
                'category' => 'scenic',
                'latitude' => -24.8757104,
                'longitude' => 113.6296854,
                'address' => 'Annear Pl, Carnarvon WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'One Mile Jetty Museum — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_oyster_bridge_bateman_sanctuary_zone',
                'name' => 'Oyster Bridge, Bateman Sanctuary Zone',
                'category' => 'scenic',
                'latitude' => -23.0713632,
                'longitude' => 113.81613480000001,
                'address' => 'Unnamed Road, Lyndon WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Oyster Bridge, Bateman Sanctuary Zone — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_oyster_stacks_snorkelling_area',
                'name' => 'Oyster Stacks Snorkelling Area',
                'category' => 'scenic',
                'latitude' => -22.1325,
                'longitude' => 113.8769444,
                'address' => 'Cape Range National Park WA 6707, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Oyster Stacks Snorkelling Area — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_paradise_beach',
                'name' => 'Paradise Beach',
                'category' => 'scenic',
                'latitude' => -23.146096099999998,
                'longitude' => 113.7669428,
                'address' => 'Lyndon WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Paradise Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_pebble_beach',
                'name' => 'Pebble Beach',
                'category' => 'scenic',
                'latitude' => -22.0358265,
                'longitude' => 114.1151369,
                'address' => 'Pebble Beach, North West Cape WA, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Pebble Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_pelican_point',
                'name' => 'Pelican Point',
                'category' => 'scenic',
                'latitude' => -23.371281200000002,
                'longitude' => 113.7869554,
                'address' => 'Lyndon WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Pelican Point — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_pelican_point_beach',
                'name' => 'Pelican Point Beach',
                'category' => 'scenic',
                'latitude' => -24.8949596,
                'longitude' => 113.63856229999999,
                'address' => '4J4Q+2C, Babbage Island WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Pelican Point Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_pelican_point_reserve',
                'name' => 'Pelican Point Reserve',
                'category' => 'parks',
                'latitude' => -24.8745692,
                'longitude' => 113.6546635,
                'address' => 'Babbage Island Rd, Morgantown WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Pelican Point Reserve — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_peoples_park',
                'name' => 'Peoples Park',
                'category' => 'scenic',
                'latitude' => -23.143470699999998,
                'longitude' => 113.77100259999999,
                'address' => 'LOT 13 Robinson St, Coral Bay WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Peoples Park — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_peron_heritage_precinct',
                'name' => 'Peron Heritage Precinct',
                'category' => 'scenic',
                'latitude' => -25.838632999999998,
                'longitude' => 113.5563128,
                'address' => 'Peron Rd, Francois Peron Nat\'l Park WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Peron Heritage Precinct — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_pimbee_national_park',
                'name' => 'Pimbee National Park',
                'category' => 'parks',
                'latitude' => -25.5435297,
                'longitude' => 115.0228736,
                'address' => 'Gascoyne River WA 6705, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Pimbee National Park — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_pogey_pearls_pastoralism',
                'name' => 'Pogey, Pearls & Pastoralism',
                'category' => 'scenic',
                'latitude' => -25.9273107,
                'longitude' => 113.53191659999999,
                'address' => 'Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Pogey, Pearls & Pastoralism — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_quobba_blow_holes',
                'name' => 'Quobba Blow Holes',
                'category' => 'scenic',
                'latitude' => -24.4812083,
                'longitude' => 113.40802169999999,
                'address' => 'MacLeod WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Quobba Blow Holes — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_quobba_station',
                'name' => 'Quobba Station',
                'category' => 'scenic',
                'latitude' => -24.3954402,
                'longitude' => 113.4062086,
                'address' => 'Gnaraloo Rd, MacLeod WA 6701, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Quobba Station — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_sandy_bay',
                'name' => 'Sandy bay',
                'category' => 'scenic',
                'latitude' => -22.2318237,
                'longitude' => 113.8427169,
                'address' => 'Sandy bay, Cape Range National Park WA 6707, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Sandy bay — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_shark_bay_district',
                'name' => 'Shark Bay District',
                'category' => 'scenic',
                'latitude' => -25.9281139,
                'longitude' => 113.5351859,
                'address' => '61 Knight Terrace, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Shark Bay District — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_shark_bay_kite_surfing',
                'name' => 'Shark Bay Kite Surfing',
                'category' => 'scenic',
                'latitude' => -25.9170195,
                'longitude' => 113.5178662,
                'address' => 'Nicholson Point, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Shark Bay Kite Surfing — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_shark_bay_marine_park',
                'name' => 'Shark Bay Marine Park',
                'category' => 'scenic',
                'latitude' => -25.929405,
                'longitude' => 113.5376517,
                'address' => '89 Knight Terrace, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Shark Bay Marine Park — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_shark_bay_views',
                'name' => 'Shark Bay Views',
                'category' => 'scenic',
                'latitude' => -25.923818999999998,
                'longitude' => 113.536429,
                'address' => '58 Durlacher St, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Shark Bay Views — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_shark_bay_world_heritage_discovery_visitor_centre',
                'name' => 'Shark Bay World Heritage Discovery & Visitor Centre',
                'category' => 'scenic',
                'latitude' => -25.9280024,
                'longitude' => 113.5348867,
                'address' => '53 Knight Terrace, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Shark Bay World Heritage Discovery & Visitor Centre — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_shark_sanctuary',
                'name' => 'Shark Sanctuary',
                'category' => 'scenic',
                'latitude' => -23.133235900000003,
                'longitude' => 113.77087519999999,
                'address' => 'Lyndon WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Shark Sanctuary — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_shell_beach',
                'name' => 'Shell Beach',
                'category' => 'scenic',
                'latitude' => -26.215,
                'longitude' => 113.7736111,
                'address' => 'Shell Beach, Western Australia 6537, Australia',
                'tier' => 5,
                'is_major_destination' => true,
                'description' => 'Shell Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_shell_beach_conservation_park',
                'name' => 'Shell Beach Conservation Park',
                'category' => 'parks',
                'latitude' => -26.204286699999997,
                'longitude' => 113.7543578,
                'address' => 'Francois Peron Nat\'l Park WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Shell Beach Conservation Park — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_shothole_canyon',
                'name' => 'Shothole Canyon',
                'category' => 'scenic',
                'latitude' => -22.065113999999998,
                'longitude' => 114.0107479,
                'address' => 'Shothole Canyon Rd, North West Cape WA 6707, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Shothole Canyon — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_skeleton_beach',
                'name' => 'Skeleton Beach',
                'category' => 'scenic',
                'latitude' => -23.120389900000003,
                'longitude' => 113.76049379999999,
                'address' => 'Skeleton Beach, Lyndon WA, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Skeleton Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_skipjack_point',
                'name' => 'Skipjack Point',
                'category' => 'scenic',
                'latitude' => -25.5138432,
                'longitude' => 113.51647910000001,
                'address' => 'Francois Peron Nat\'l Park WA 6537, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Skipjack Point — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_south_lefroy_bay_ningaloo_station',
                'name' => 'South Lefroy Bay , (Ningaloo Station)',
                'category' => 'scenic',
                'latitude' => -22.5520446,
                'longitude' => 113.66477979999999,
                'address' => 'Unnamed Road, Ningaloo WA 6701, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'South Lefroy Bay , (Ningaloo Station) — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_steep_point',
                'name' => 'Steep Point',
                'category' => 'parks',
                'latitude' => -26.144578,
                'longitude' => 113.159092,
                'address' => 'Carrarang WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Steep Point — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_stella_rowley_drive_lookout',
                'name' => 'Stella Rowley Drive Lookout',
                'category' => 'scenic',
                'latitude' => -25.9200903,
                'longitude' => 113.522448,
                'address' => 'Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Stella Rowley Drive Lookout — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_sunday_island_bay',
                'name' => 'Sunday Island Bay',
                'category' => 'scenic',
                'latitude' => -26.1346427,
                'longitude' => 113.2251251,
                'address' => 'V68G+43, Dirk Hartog Island WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Sunday Island Bay — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_tamala_station',
                'name' => 'Tamala Station',
                'category' => 'scenic',
                'latitude' => -26.696237999999997,
                'longitude' => 113.715705,
                'address' => 'Tamala Road, Shark Bay WA 6537, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Tamala Station — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_temple_gorge',
                'name' => 'Temple Gorge',
                'category' => 'parks',
                'latitude' => -24.6611537,
                'longitude' => 115.16978329999999,
                'address' => 'Kennedy Range WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Temple Gorge — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_temple_gorge_campground',
                'name' => 'Temple Gorge Campground',
                'category' => 'parks',
                'latitude' => -24.661668499999998,
                'longitude' => 115.17415459999998,
                'address' => 'Unnamed Road, Kennedy Range WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Temple Gorge Campground — a wild Gascoyne park of red earth, rugged ranges and big quiet skies, well off the beaten track.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gas_tetradon_loop',
                'name' => 'Tetradon Loop',
                'category' => 'scenic',
                'latitude' => -25.9434725,
                'longitude' => 113.1423545,
                'address' => '344R+JW, Dirk Hartog Island WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Tetradon Loop — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_the_old_pearler_denham_discovery_traill',
                'name' => 'The Old Pearler/Denham Discovery Traill',
                'category' => 'scenic',
                'latitude' => -25.9287212,
                'longitude' => 113.5358602,
                'address' => '71 Knight Terrace, Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'The Old Pearler/Denham Discovery Traill — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_the_thong_shack',
                'name' => 'The Thong Shack',
                'category' => 'scenic',
                'latitude' => -25.949236,
                'longitude' => 113.559472,
                'address' => 'Denham WA 6537, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'The Thong Shack — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_town_beach',
                'name' => 'Town Beach',
                'category' => 'scenic',
                'latitude' => -21.9518895,
                'longitude' => 114.138919,
                'address' => 'Town Beach, Exmouth WA, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Town Beach — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_gas_turquoise_bay',
                'name' => 'Turquoise Bay',
                'category' => 'scenic',
                'latitude' => -22.0978565,
                'longitude' => 113.8881097,
                'address' => 'Turquoise Bay, Cape Range National Park WA 6707, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Turquoise Bay — a striking Gascoyne coastal spot of turquoise water, white sand and far-horizon views worth the journey north.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
        ];

        foreach ($locations as $data) {
            $data['points'] = Location::defaultPointsForTier($data['tier']);

            Location::updateOrCreate(
                ['name' => $data['name']],
                array_merge($data, [
                    'verification_tags' => [],
                    'active' => true,
                    'status' => Location::STATUS_APPROVED,
                    'submitted_by' => null,
                ])
            );
        }
    }
}
