<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

/**
 * REAL public Locatour locations across the Peel region of Western Australia
 * (Mandurah, Dwellingup, Pinjarra and surrounds), sourced from the Google
 * Places API (New) Text Search and deduped by Places id.
 *
 * Idempotent: upserts keyed on `name`. A unique `slug` is supplied for the
 * NOT-NULL unique column. points is set from Location::defaultPointsForTier()
 * so the explicit tier and the model's saving() hook (which re-derives tier
 * from points) stay consistent. updateOrCreate runs save(), firing that hook.
 */
class WaBulkPeelSeeder extends Seeder
{
    public function run(): void
    {
        $locations = [
            [
                'name' => 'Amaze Miniature Park',
                'slug' => 'peel_amaze_miniature_park',
                'category' => 'scenic',
                'latitude' => -32.5477053,
                'longitude' => 115.7777577,
                'address' => '24 Husband Rd, Barragup WA 6209, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Amaze Miniature Park, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Avalon Beach',
                'slug' => 'peel_avalon_beach__d18',
                'category' => 'scenic',
                'latitude' => -32.5886789,
                'longitude' => 115.6413532,
                'address' => 'Avalon Foreshore Reserve, 5 Avalon Parade, Falcon WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A relaxed Peel-region beach at Avalon Beach, with clear water, soft sand and easy coastal walks.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Baldivis Nature Reserve',
                'slug' => 'peel_baldivis_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.3063841,
                'longitude' => 115.8189493,
                'address' => '214 Fifty Rd, Baldivis WA 6171, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Baldivis Nature Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Beelu National Park',
                'slug' => 'peel_beelu_national_park',
                'category' => 'parks',
                'latitude' => -31.9517529,
                'longitude' => 116.1735423,
                'address' => 'Mundaring Weir Rd, Mundaring WA 6073, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Beelu National Park, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Big Tree',
                'slug' => 'peel_big_tree',
                'category' => 'parks',
                'latitude' => -32.5395902,
                'longitude' => 115.7609657,
                'address' => '4 Old Pinjarra Rd, Greenfields WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Big Tree, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Bortolo Park',
                'slug' => 'peel_bortolo_park',
                'category' => 'parks',
                'latitude' => -32.5291667,
                'longitude' => 115.7533333,
                'address' => '75 Murdoch Dr, Greenfields WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Bortolo Park, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Caddadup Reserve',
                'slug' => 'peel_caddadup_reserve',
                'category' => 'parks',
                'latitude' => -32.6151893,
                'longitude' => 115.6299078,
                'address' => '1000L Old Coast Rd, Dawesville WA 6211, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Caddadup Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Cafe Moka',
                'slug' => 'peel_cafe_moka',
                'category' => 'food',
                'latitude' => -32.5235736,
                'longitude' => 115.7177228,
                'address' => '18/4 Zephyr Mews, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at Cafe Moka — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'Café René Mandurah',
                'slug' => 'peel_caf_ren_mandurah',
                'category' => 'food',
                'latitude' => -32.5272267,
                'longitude' => 115.7177549,
                'address' => '22 Ormsby Terrace, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at Café René Mandurah — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'Contemporary Art Spaces Mandurah',
                'slug' => 'peel_contemporary_art_spaces_mandurah',
                'category' => 'scenic',
                'latitude' => -32.5262801,
                'longitude' => 115.7204249,
                'address' => '63 Ormsby Terrace, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Contemporary Art Spaces Mandurah, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Coodanup Foreshore Reserve',
                'slug' => 'peel_coodanup_foreshore_reserve',
                'category' => 'parks',
                'latitude' => -32.562194,
                'longitude' => 115.7439436,
                'address' => 'Mandurah Regional Districts WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A breezy waterfront spot at Coodanup Foreshore Reserve, where the estuary, jetties and boardwalks draw walkers, fishers and dolphins alike.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Creery Wetland Nature Reserve',
                'slug' => 'peel_creery_wetland_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.5545944,
                'longitude' => 115.7335404,
                'address' => 'Dudley Park WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Creery Wetland Nature Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Creery Wetland Nature Reserve Lookout',
                'slug' => 'peel_creery_wetland_nature_reserve_lookout',
                'category' => 'scenic',
                'latitude' => -32.5573916,
                'longitude' => 115.7318573,
                'address' => 'Darwin Terrace, Dudley Park WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Creery Wetland Nature Reserve Lookout, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Creery Wetland Reserve',
                'slug' => 'peel_creery_wetland_reserve',
                'category' => 'parks',
                'latitude' => -32.5618545,
                'longitude' => 115.7412018,
                'address' => 'Wanjeep St, Coodanup WA 6210, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Creery Wetland Reserve, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Dawesville Foreshore Reserve',
                'slug' => 'peel_dawesville_foreshore_reserve',
                'category' => 'parks',
                'latitude' => -32.6248515,
                'longitude' => 115.6414052,
                'address' => '170 Estuary Rd, Dawesville WA 6211, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A breezy waterfront spot at Dawesville Foreshore Reserve, where the estuary, jetties and boardwalks draw walkers, fishers and dolphins alike.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Detour Cafe Dolphin Quay',
                'slug' => 'peel_detour_cafe_dolphin_quay',
                'category' => 'food',
                'latitude' => -32.5237011,
                'longitude' => 115.7177922,
                'address' => '4 Zephyr Mews, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at Detour Cafe Dolphin Quay — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'Dwaarlindjirraap Day Use Area',
                'slug' => 'peel_dwaarlindjirraap_day_use_area',
                'category' => 'parks',
                'latitude' => -32.7716257,
                'longitude' => 116.0844792,
                'address' => 'Unnamed Road, Dwellingup WA 6213, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Dwaarlindjirraap Day Use Area, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Dwellingup Dinner Train',
                'slug' => 'peel_dwellingup_dinner_train',
                'category' => 'scenic',
                'latitude' => -32.7118018,
                'longitude' => 116.0625241,
                'address' => '4 Marinup St, Dwellingup WA 6213, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Dwellingup Dinner Train, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Edenvale Heritage Precinct',
                'slug' => 'peel_edenvale_heritage_precinct',
                'category' => 'scenic',
                'latitude' => -32.6270763,
                'longitude' => 115.8756945,
                'address' => '1 George St, Pinjarra WA 6208, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Edenvale Heritage Precinct, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Ellis Brook Falls',
                'slug' => 'peel_ellis_brook_falls',
                'category' => 'scenic',
                'latitude' => -32.0660719,
                'longitude' => 116.040214,
                'address' => 'Martin WA 6110, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A picturesque cascade at Ellis Brook Falls, tumbling through the jarrah forest of the Darling Scarp.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Falcon Bay Lookout',
                'slug' => 'peel_falcon_bay_lookout',
                'category' => 'scenic',
                'latitude' => -32.579825,
                'longitude' => 115.650432,
                'address' => '1 Spinaway Parade, Falcon WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Falcon Bay Lookout, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Falcon Beach',
                'slug' => 'peel_falcon_beach',
                'category' => 'scenic',
                'latitude' => -32.5801397,
                'longitude' => 115.6523868,
                'address' => 'Falcon Beach, Spinaway Parade, Falcon WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A relaxed Peel-region beach at Falcon Beach, with clear water, soft sand and easy coastal walks.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Floating Jetty Western Foreshore',
                'slug' => 'peel_floating_jetty_western_foreshore',
                'category' => 'scenic',
                'latitude' => -32.5338472,
                'longitude' => 115.7163917,
                'address' => 'Halls Head WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A breezy waterfront spot at Floating Jetty Western Foreshore, where the estuary, jetties and boardwalks draw walkers, fishers and dolphins alike.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Frasers Landing Pond',
                'slug' => 'peel_frasers_landing_pond',
                'category' => 'parks',
                'latitude' => -32.5479595,
                'longitude' => 115.7551691,
                'address' => '30 Pardoo La, Coodanup WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Frasers Landing Pond, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Friends of the Lakes - NORTH YUNDERUP',
                'slug' => 'peel_friends_of_the_lakes_north_yunderup',
                'category' => 'parks',
                'latitude' => -32.5722022,
                'longitude' => 115.7910728,
                'address' => 'Conservation Area, N Yunderup Rd, North Yunderup WA 6208, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Friends of the Lakes - NORTH YUNDERUP, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Goegrup Lake',
                'slug' => 'peel_goegrup_lake',
                'category' => 'parks',
                'latitude' => -32.5211111,
                'longitude' => 115.7822222,
                'address' => 'Goegrup Lake, Barragup WA 6209, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A scenic lake at Goegrup Lake, perfect for a peaceful stroll, birdwatching and reflections at golden hour.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Goegrup Lake Nature Reserve',
                'slug' => 'peel_goegrup_lake_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.5154015,
                'longitude' => 115.7782286,
                'address' => 'Western Australia, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A scenic lake at Goegrup Lake Nature Reserve, perfect for a peaceful stroll, birdwatching and reflections at golden hour.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Goegrup Nature Reserve',
                'slug' => 'peel_goegrup_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.5235153,
                'longitude' => 115.7936902,
                'address' => 'Dunkerton Rd, Barragup WA 6209, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Goegrup Nature Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Golden Bay Foreshore Reserve',
                'slug' => 'peel_golden_bay_foreshore_reserve',
                'category' => 'parks',
                'latitude' => -32.4273241,
                'longitude' => 115.7503009,
                'address' => 'for shore, Marillana Dr, Golden Bay WA 6174, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Golden Bay Foreshore Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Hall Park',
                'slug' => 'peel_hall_park',
                'category' => 'parks',
                'latitude' => -32.5351464,
                'longitude' => 115.7146195,
                'address' => 'FP78+VC, 1 Leighton Pl, Halls Head WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Hall Park, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Hall\'s Cottage',
                'slug' => 'peel_hall_s_cottage',
                'category' => 'scenic',
                'latitude' => -32.5336073,
                'longitude' => 115.7135469,
                'address' => 'Halls Head WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Hall\'s Cottage, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Halls Head Beach',
                'slug' => 'peel_halls_head_beach',
                'category' => 'scenic',
                'latitude' => -32.5199644,
                'longitude' => 115.7007467,
                'address' => 'Halls Head Beach, Western Australia, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A relaxed Peel-region beach at Halls Head Beach, with clear water, soft sand and easy coastal walks.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Henry Sutton Grove',
                'slug' => 'peel_henry_sutton_grove',
                'category' => 'parks',
                'latitude' => -32.5308261,
                'longitude' => 115.712953,
                'address' => 'Halls Head WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Henry Sutton Grove, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'HIMVANTA Mural',
                'slug' => 'peel_himvanta_mural',
                'category' => 'scenic',
                'latitude' => -32.5333956,
                'longitude' => 115.7198072,
                'address' => 'Smart St, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at HIMVANTA Mural, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Hotham Valley Railway',
                'slug' => 'peel_hotham_valley_railway',
                'category' => 'scenic',
                'latitude' => -32.7118175,
                'longitude' => 116.0627496,
                'address' => 'Marinup St, Dwellingup WA 6213, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Hotham Valley Railway, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'James Service Memorial Sculpture',
                'slug' => 'peel_james_service_memorial_sculpture',
                'category' => 'scenic',
                'latitude' => -32.5213719,
                'longitude' => 115.712407,
                'address' => 'Breakwater Parade, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at James Service Memorial Sculpture, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Joseph and Dulcie Nannup Trail',
                'slug' => 'peel_joseph_and_dulcie_nannup_trail',
                'category' => 'parks',
                'latitude' => -32.542013,
                'longitude' => 115.7676306,
                'address' => 'Old Pinjarra Rd, Greenfields WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A green community space at Joseph and Dulcie Nannup Trail, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Kalamunda National Park',
                'slug' => 'peel_kalamunda_national_park',
                'category' => 'parks',
                'latitude' => -31.9690523,
                'longitude' => 116.0776791,
                'address' => 'Schipp Rd, Piesse Brook WA 6076, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Kalamunda National Park, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Kangaroo Paw Park',
                'slug' => 'peel_kangaroo_paw_park',
                'category' => 'parks',
                'latitude' => -32.5225038,
                'longitude' => 115.7515125,
                'address' => '2F Montana Lp, Greenfields WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Kangaroo Paw Park, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Korung National Park',
                'slug' => 'peel_korung_national_park',
                'category' => 'parks',
                'latitude' => -32.0574203,
                'longitude' => 116.0956165,
                'address' => 'Canning Mills WA 6111, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Korung National Park, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Lake Clifton Thrombolites',
                'slug' => 'peel_lake_clifton_thrombolites',
                'category' => 'scenic',
                'latitude' => -32.7452381,
                'longitude' => 115.6540015,
                'address' => 'Lake Clifton WA 6215, Australia',
                'tier' => 2,
                'is_major_destination' => true,
                'description' => 'Boardwalk over ancient living rock-like microbial structures on the shores of Lake Clifton — among the largest thrombolite formations on Earth.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Lake Navarino',
                'slug' => 'peel_lake_navarino',
                'category' => 'parks',
                'latitude' => -32.8399316,
                'longitude' => 115.9876604,
                'address' => '147 Invarell Rd, Waroona WA 6215, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Lake Navarino, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Lake Pollard',
                'slug' => 'peel_lake_pollard',
                'category' => 'parks',
                'latitude' => -32.8202778,
                'longitude' => 115.6616667,
                'address' => 'Lake Pollard, Preston Beach WA 6215, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A scenic lake at Lake Pollard, perfect for a peaceful stroll, birdwatching and reflections at golden hour.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Leda Nature Reserve',
                'slug' => 'peel_leda_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.2765274,
                'longitude' => 115.8078102,
                'address' => '206 Runnymede Gate, Leda WA 6170, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Leda Nature Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Len Howard Conservation Park',
                'slug' => 'peel_len_howard_conservation_park',
                'category' => 'parks',
                'latitude' => -32.5617385,
                'longitude' => 115.7020413,
                'address' => 'CMHM+CR, 21 Len Howard Dr, Erskine WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Len Howard Conservation Park, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Lesmurdie Falls National Park',
                'slug' => 'peel_lesmurdie_falls_national_park',
                'category' => 'parks',
                'latitude' => -31.9950526,
                'longitude' => 116.0332615,
                'address' => '160/186 Falls Rd, Forrestfield WA 6058, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Lesmurdie Falls National Park, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Little Mermaid Beach at Stingray Point',
                'slug' => 'peel_little_mermaid_beach_at_stingray_point',
                'category' => 'parks',
                'latitude' => -32.5288457,
                'longitude' => 115.71575,
                'address' => 'Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A relaxed Peel-region beach at Little Mermaid Beach at Stingray Point, with clear water, soft sand and easy coastal walks.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Madora Beach',
                'slug' => 'peel_madora_beach',
                'category' => 'scenic',
                'latitude' => -32.4613672,
                'longitude' => 115.7469796,
                'address' => 'Madora Beach, Western Australia, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A relaxed Peel-region beach at Madora Beach, with clear water, soft sand and easy coastal walks.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Mandurah Boardwalk',
                'slug' => 'peel_mandurah_boardwalk',
                'category' => 'scenic',
                'latitude' => -32.528676,
                'longitude' => 115.72038,
                'address' => '73 Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Mandurah Boardwalk, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Mandurah Eastern Foreshore',
                'slug' => 'peel_mandurah_eastern_foreshore',
                'category' => 'scenic',
                'latitude' => -32.5326461,
                'longitude' => 115.7191502,
                'address' => '17 Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => true,
                'description' => 'A breezy waterfront spot at Mandurah Eastern Foreshore, where the estuary, jetties and boardwalks draw walkers, fishers and dolphins alike.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Mandurah Estuary',
                'slug' => 'peel_mandurah_estuary',
                'category' => 'parks',
                'latitude' => -32.5383151,
                'longitude' => 115.7183919,
                'address' => 'Mandurah WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Mandurah Estuary, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Mandurah Museum',
                'slug' => 'peel_mandurah_museum',
                'category' => 'scenic',
                'latitude' => -32.535017,
                'longitude' => 115.719595,
                'address' => '3 Pinjarra Rd, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Mandurah Museum, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Mandurah Visitor Centre',
                'slug' => 'peel_mandurah_visitor_centre',
                'category' => 'scenic',
                'latitude' => -32.5285141,
                'longitude' => 115.7205455,
                'address' => '75 Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Mandurah Visitor Centre, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Mandurah War Memorial',
                'slug' => 'peel_mandurah_war_memorial',
                'category' => 'parks',
                'latitude' => -32.531887,
                'longitude' => 115.7145859,
                'address' => '11 Leighton Pl, Halls Head WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Mandurah War Memorial, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Marlee Reserve',
                'slug' => 'peel_marlee_reserve',
                'category' => 'parks',
                'latitude' => -32.4886749,
                'longitude' => 115.7729984,
                'address' => '101 Marlee Rd, Parklands WA 6180, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Marlee Reserve, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Marrinup Falls Walk Trail',
                'slug' => 'peel_marrinup_falls_walk_trail',
                'category' => 'parks',
                'latitude' => -32.6921778,
                'longitude' => 116.0040613,
                'address' => 'Grey Rd, Marrinup WA 6213, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A picturesque cascade at Marrinup Falls Walk Trail, tumbling through the jarrah forest of the Darling Scarp.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Marrinup P.O.W camp',
                'slug' => 'peel_marrinup_p_o_w_camp',
                'category' => 'scenic',
                'latitude' => -32.6938638,
                'longitude' => 116.0261118,
                'address' => 'Grey Rd, Marrinup WA 6213, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Marrinup P.O.W camp, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Mataya Eatery',
                'slug' => 'peel_mataya_eatery',
                'category' => 'food',
                'latitude' => -32.5322372,
                'longitude' => 115.7210303,
                'address' => '20 Sholl St, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at Mataya Eatery — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'Midgegooroo National Park',
                'slug' => 'peel_midgegooroo_national_park',
                'category' => 'parks',
                'latitude' => -32.11013,
                'longitude' => 116.1422072,
                'address' => 'Logger Rd, Karragullen WA 6111, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Midgegooroo National Park, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Nature\'s Eye Shelter',
                'slug' => 'peel_nature_s_eye_shelter',
                'category' => 'scenic',
                'latitude' => -32.5715235,
                'longitude' => 115.6852487,
                'address' => 'Erskine WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Nature\'s Eye Shelter, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Newman Reserve',
                'slug' => 'peel_newman_reserve',
                'category' => 'parks',
                'latitude' => -32.4047676,
                'longitude' => 115.7668789,
                'address' => '39 Maroubra Parade, Secret Harbour WA 6173, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Newman Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Norma & Allan Withers Reserve',
                'slug' => 'peel_norma_allan_withers_reserve',
                'category' => 'parks',
                'latitude' => -32.4764808,
                'longitude' => 115.7489964,
                'address' => '7/23 Tranby St, Madora Bay WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Norma & Allan Withers Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'North Dandalup Dam',
                'slug' => 'peel_north_dandalup_dam',
                'category' => 'scenic',
                'latitude' => -32.5188931,
                'longitude' => 116.0149717,
                'address' => 'Scarp Rd, Whittaker WA 6207, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at North Dandalup Dam, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'North Yunderup Conservation Area',
                'slug' => 'peel_north_yunderup_conservation_area',
                'category' => 'parks',
                'latitude' => -32.5728044,
                'longitude' => 115.7911265,
                'address' => 'N Yunderup Rd, North Yunderup WA 6208, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at North Yunderup Conservation Area, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Novara Foreshore Reserve',
                'slug' => 'peel_novara_foreshore_reserve',
                'category' => 'parks',
                'latitude' => -32.5719504,
                'longitude' => 115.6790977,
                'address' => 'Dampier Ave, Falcon WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A breezy waterfront spot at Novara Foreshore Reserve, where the estuary, jetties and boardwalks draw walkers, fishers and dolphins alike.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Nyoongar Trail',
                'slug' => 'peel_nyoongar_trail',
                'category' => 'parks',
                'latitude' => -32.3742219,
                'longitude' => 115.8242464,
                'address' => '19/21 Karnup Rd, Baldivis WA 6171, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Nyoongar Trail, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Oakley Dam',
                'slug' => 'peel_oakley_dam',
                'category' => 'scenic',
                'latitude' => -32.6539907,
                'longitude' => 115.969543,
                'address' => 'Marrinup WA 6213, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Oakley Dam, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Old Blythewood on Bindjareb Noongar Country',
                'slug' => 'peel_old_blythewood_on_bindjareb_noongar_country',
                'category' => 'scenic',
                'latitude' => -32.6622217,
                'longitude' => 115.8670103,
                'address' => '6161 S Western Hwy, Pinjarra WA 6208, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Old Blythewood on Bindjareb Noongar Country, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Orion Reserve',
                'slug' => 'peel_orion_reserve',
                'category' => 'parks',
                'latitude' => -32.5100123,
                'longitude' => 115.7329034,
                'address' => 'Silver Sands WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Orion Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Paganoni road',
                'slug' => 'peel_paganoni_road',
                'category' => 'parks',
                'latitude' => -32.4338501,
                'longitude' => 115.785137,
                'address' => '125 Paganoni Rd, Karnup WA 6176, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Paganoni road, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Perch’d',
                'slug' => 'peel_perch_d',
                'category' => 'food',
                'latitude' => -32.5329623,
                'longitude' => 115.7194642,
                'address' => '30 Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at Perch’d — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'Perth 旅行 泰餐',
                'slug' => 'peel_perth',
                'category' => 'scenic',
                'latitude' => -32.5341858,
                'longitude' => 115.7186361,
                'address' => '5a Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Perth 旅行 泰餐, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Piney Lakes Reserve',
                'slug' => 'peel_piney_lakes_reserve',
                'category' => 'parks',
                'latitude' => -32.0496183,
                'longitude' => 115.8386885,
                'address' => '555 Leach Hwy, Winthrop WA 6150, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Piney Lakes Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Pinjarra Community Garden',
                'slug' => 'peel_pinjarra_community_garden',
                'category' => 'parks',
                'latitude' => -32.6302524,
                'longitude' => 115.8795904,
                'address' => '1 Fimmel Ln, Pinjarra WA 6208, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Pinjarra Community Garden, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Point Grey',
                'slug' => 'peel_point_grey',
                'category' => 'parks',
                'latitude' => -32.6522293,
                'longitude' => 115.6797331,
                'address' => 'Point Grey WA 6208, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Point Grey, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Point Morfitt',
                'slug' => 'peel_point_morfitt',
                'category' => 'parks',
                'latitude' => -32.6614212,
                'longitude' => 115.6565586,
                'address' => 'Mulberry Cl, Bouvard WA 6211, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Point Morfitt, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Quarry Adventure Park',
                'slug' => 'peel_quarry_adventure_park',
                'category' => 'parks',
                'latitude' => -32.4927405,
                'longitude' => 115.7609869,
                'address' => 'Lot 1890 Pebble Beach Blvd, Meadow Springs WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Quarry Adventure Park, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Reserve Drive Reserve',
                'slug' => 'peel_reserve_drive_reserve',
                'category' => 'parks',
                'latitude' => -32.518479,
                'longitude' => 115.7442896,
                'address' => 'Reserve Dr, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Reserve Drive Reserve, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Rockingham Lakes Regional Park',
                'slug' => 'peel_rockingham_lakes_regional_park',
                'category' => 'parks',
                'latitude' => -32.3137012,
                'longitude' => 115.7818554,
                'address' => 'Waikiki WA 6169, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Rockingham Lakes Regional Park, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Samphire Cove Reserve',
                'slug' => 'peel_samphire_cove_reserve',
                'category' => 'parks',
                'latitude' => -32.5482949,
                'longitude' => 115.7137189,
                'address' => 'Cnr Wedgetail Retreat &, Egret Point Rd, Halls Head WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Samphire Cove Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Samphire Point',
                'slug' => 'peel_samphire_point',
                'category' => 'parks',
                'latitude' => -32.5387079,
                'longitude' => 115.7197926,
                'address' => 'Dudley Park WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Samphire Point, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Scarp Pool',
                'slug' => 'peel_scarp_pool',
                'category' => 'scenic',
                'latitude' => -32.7648838,
                'longitude' => 115.9978613,
                'address' => 'Scarp Rd, Teesdale WA 6213, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Scarp Pool, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Serpentine Falls',
                'slug' => 'peel_serpentine_falls_ra7s',
                'category' => 'scenic',
                'latitude' => -32.3680204,
                'longitude' => 116.0113251,
                'address' => 'Serpentine Falls, Serpentine WA 6125, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A picturesque cascade at Serpentine Falls, tumbling through the jarrah forest of the Darling Scarp.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Serpentine Main Dam',
                'slug' => 'peel_serpentine_main_dam',
                'category' => 'scenic',
                'latitude' => -32.4038317,
                'longitude' => 116.099489,
                'address' => 'Serpentine WA 6125, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Serpentine Main Dam, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Serpentine National Park',
                'slug' => 'peel_serpentine_national_park',
                'category' => 'parks',
                'latitude' => -32.370414,
                'longitude' => 116.0017585,
                'address' => '100 Falls Rd, Serpentine WA 6125, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Serpentine National Park, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Serpentine River Nature Reserve',
                'slug' => 'peel_serpentine_river_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.501346,
                'longitude' => 115.790464,
                'address' => '227 Woodland Parade, Stake Hill WA 6181, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Serpentine River Nature Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Shoalwater Islands Marine Park',
                'slug' => 'peel_shoalwater_islands_marine_park',
                'category' => 'parks',
                'latitude' => -32.302921,
                'longitude' => 115.701991,
                'address' => '153 Arcadia Dr, Rockingham WA 6169, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Shoalwater Islands Marine Park, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Silver Sand Beach',
                'slug' => 'peel_silver_sand_beach',
                'category' => 'scenic',
                'latitude' => -32.5177143,
                'longitude' => 115.7265456,
                'address' => 'Silver Sand Beach, Western Australia, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A relaxed Peel-region beach at Silver Sand Beach, with clear water, soft sand and easy coastal walks.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'SILVER SANDS BEACH',
                'slug' => 'peel_silver_sands_beach',
                'category' => 'scenic',
                'latitude' => -32.5173363,
                'longitude' => 115.7282288,
                'address' => 'Henson St, Silver Sands WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A relaxed Peel-region beach at SILVER SANDS BEACH, with clear water, soft sand and easy coastal walks.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Sticks Channel',
                'slug' => 'peel_sticks_channel',
                'category' => 'parks',
                'latitude' => -32.5657464,
                'longitude' => 115.7091075,
                'address' => '15 Conservation Loop, Erskine WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Sticks Channel, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Stingray Point Reserve',
                'slug' => 'peel_stingray_point_reserve',
                'category' => 'parks',
                'latitude' => -32.5295647,
                'longitude' => 115.7168068,
                'address' => 'Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A green community space at Stingray Point Reserve, with shady lawns, trails and picnic spots for an easy day outdoors.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'name' => 'Swan Estuary Marine Park',
                'slug' => 'peel_swan_estuary_marine_park',
                'category' => 'parks',
                'latitude' => -31.9862728,
                'longitude' => 115.8274848,
                'address' => 'Crawley WA 6009, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Swan Estuary Marine Park, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Tamworth Wetlands',
                'slug' => 'peel_tamworth_wetlands',
                'category' => 'parks',
                'latitude' => -32.3243124,
                'longitude' => 115.8087238,
                'address' => '242 Eighty Rd, Baldivis WA 6171, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Tamworth Wetlands, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Tern Island Nature Reserve',
                'slug' => 'peel_tern_island_nature_reserve',
                'category' => 'parks',
                'latitude' => -32.3082621,
                'longitude' => 115.7154181,
                'address' => 'Rockingham WA 6168, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Tern Island Nature Reserve, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'The Bay Cafe Mandurah',
                'slug' => 'peel_the_bay_cafe_mandurah',
                'category' => 'food',
                'latitude' => -32.5338696,
                'longitude' => 115.7184749,
                'address' => 'Unit 5/9 Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at The Bay Cafe Mandurah — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'The Chimneys',
                'slug' => 'peel_the_chimneys',
                'category' => 'parks',
                'latitude' => -32.5578054,
                'longitude' => 115.7162563,
                'address' => 'Erskine WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at The Chimneys, alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'The Hummingbird Waterside Cafe',
                'slug' => 'peel_the_hummingbird_waterside_cafe',
                'category' => 'food',
                'latitude' => -32.532293,
                'longitude' => 115.719926,
                'address' => '1/38 Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at The Hummingbird Waterside Cafe — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'Tods Cafe Mandurah',
                'slug' => 'peel_tods_cafe_mandurah',
                'category' => 'food',
                'latitude' => -32.5289373,
                'longitude' => 115.7202025,
                'address' => 'The Boardwalk, 73 Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at Tods Cafe Mandurah — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'Town Beach',
                'slug' => 'peel_town_beach',
                'category' => 'scenic',
                'latitude' => -32.5192324,
                'longitude' => 115.7248812,
                'address' => 'Town Beach, Mandurah WA, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A relaxed Peel-region beach at Town Beach, with clear water, soft sand and easy coastal walks.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'name' => 'Treetops Adventure Dwellingup',
                'slug' => 'peel_treetops_adventure_dwellingup',
                'category' => 'scenic',
                'latitude' => -32.805306,
                'longitude' => 116.095083,
                'address' => 'Lane Poole Reserve, Off Nanga Rd, Dwellingup WA 6213, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Treetops Adventure Dwellingup, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Turquoise Mandurah',
                'slug' => 'peel_turquoise_mandurah',
                'category' => 'food',
                'latitude' => -32.5233542,
                'longitude' => 115.7178833,
                'address' => 'Shop 1 & 2/37 Dolphin Dr, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at Turquoise Mandurah — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'Venetian Dome Art Trail No 8',
                'slug' => 'peel_venetian_dome_art_trail_no_8',
                'category' => 'scenic',
                'latitude' => -32.5259926,
                'longitude' => 115.7154851,
                'address' => 'Cannaregio Square, Mandurah WA 6210, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Venetian Dome Art Trail No 8, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Waroona Dam',
                'slug' => 'peel_waroona_dam',
                'category' => 'scenic',
                'latitude' => -32.8481044,
                'longitude' => 115.9836107,
                'address' => '147 Invarell Rd, Waroona WA 6215, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A notable Peel-region attraction at Waroona Dam, worth a stop to soak up the local scenery and character.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'name' => 'Wood and Stone Café',
                'slug' => 'peel_wood_and_stone_caf',
                'category' => 'food',
                'latitude' => -32.5323865,
                'longitude' => 115.7199054,
                'address' => '2/38 Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A welcoming local spot at Wood and Stone Café — a great place to refuel with good coffee and a bite in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'name' => 'Wungong Regional Park',
                'slug' => 'peel_wungong_regional_park',
                'category' => 'parks',
                'latitude' => -32.1999869,
                'longitude' => 116.0637874,
                'address' => 'Bedfordale WA 6112, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Wungong Regional Park, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Yaburgurt Kaaleepga Reserve (Winjan\'s Camp)',
                'slug' => 'peel_yaburgurt_kaaleepga_reserve_winjan_s_camp',
                'category' => 'parks',
                'latitude' => -32.5396653,
                'longitude' => 115.7064759,
                'address' => '55 McLarty Rd, Halls Head WA 6210, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A tranquil conservation reserve at Yaburgurt Kaaleepga Reserve (Winjan\'s Camp), alive with birdlife, wetlands and native bush close to Mandurah.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Yalgorup National Park',
                'slug' => 'peel_yalgorup_national_park',
                'category' => 'parks',
                'latitude' => -32.8446424,
                'longitude' => 115.6673397,
                'address' => 'Preston Beach Rd, Preston Beach WA 6215, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected expanse of WA bushland and wildlife at Yalgorup National Park, with walk trails and quiet natural beauty in the Peel region.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'name' => 'Yindana Lake',
                'slug' => 'peel_yindana_lake',
                'category' => 'parks',
                'latitude' => -32.4767711,
                'longitude' => 115.7668166,
                'address' => 'Yindana Blvd, Lakelands WA 6180, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A scenic lake at Yindana Lake, perfect for a peaceful stroll, birdwatching and reflections at golden hour.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
        ];

        foreach ($locations as $data) {
            // points drives tier via the model's saving() hook; use the per-tier
            // default so the explicit tier and the derived tier agree.
            $data['points'] = Location::defaultPointsForTier($data['tier']);

            Location::updateOrCreate(
                ['name' => $data['name']],
                array_merge($data, [
                    'verification_tags' => [],
                    'active' => true,
                    'status' => Location::STATUS_APPROVED,
                    'submitted_by' => null,
                ])
            );
        }
    }
}
