<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class WaBulkPilbaraSeeder extends Seeder
{
    /**
     * REAL public locations across the Pilbara / Ningaloo region of Western
     * Australia (Karijini, Exmouth, Ningaloo, Cape Range, Port/South Hedland,
     * Karratha/Dampier, Millstream-Chichester), sourced from the Google Places
     * API (New) Text Search and deduplicated by Places id.
     *
     * Idempotent: upserts keyed on `name`. points is set from the per-tier
     * default (Location::defaultPointsForTier) and the model's saving() hook
     * re-derives tier from points, so the explicit tier and derived tier agree.
     * Uses updateOrCreate (which runs save()) so that hook fires.
     */
    public function run(): void
    {
        $locations = [
            [
                'slug' => 'wa_pil_karijini_national_park',
                'name' => 'Karijini National Park',
                'category' => 'parks',
                'latitude' => -22.6751716,
                'longitude' => 118.2889234,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => true,
                'description' => 'Karijini National Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_hamersley_gorge',
                'name' => 'Hamersley Gorge',
                'category' => 'parks',
                'latitude' => -22.258321,
                'longitude' => 117.9862441,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Hamersley Gorge — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_murujuga_national_park',
                'name' => 'Murujuga National Park',
                'category' => 'parks',
                'latitude' => -20.5650541,
                'longitude' => 116.8152659,
                'address' => 'Burrup Road, Burrup WA 6714, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Murujuga National Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_millstream_chichester_national_park',
                'name' => 'Millstream Chichester National Park',
                'category' => 'parks',
                'latitude' => -21.591491,
                'longitude' => 117.07115,
                'address' => 'Kanjenjie-Millstream Rd, Millstream WA 6716, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Millstream Chichester National Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_hancock_gorge',
                'name' => 'Hancock Gorge',
                'category' => 'parks',
                'latitude' => -22.3586153,
                'longitude' => 118.2846958,
                'address' => 'Weano Rd, Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Hancock Gorge — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_weano_gorge',
                'name' => 'Weano Gorge',
                'category' => 'parks',
                'latitude' => -22.3562191,
                'longitude' => 118.2872595,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Weano Gorge — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_joffre_gorge',
                'name' => 'Joffre Gorge',
                'category' => 'parks',
                'latitude' => -22.3906385,
                'longitude' => 118.268584,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Joffre Gorge — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_cape_range_national_park',
                'name' => 'Cape Range National Park',
                'category' => 'parks',
                'latitude' => -22.0709945,
                'longitude' => 113.9774289,
                'address' => 'Yardie Creek Rd, Cape Range National Park WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => true,
                'description' => 'Cape Range National Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_knox_gorge',
                'name' => 'Knox Gorge',
                'category' => 'scenic',
                'latitude' => -22.3699978,
                'longitude' => 118.2963835,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Knox Gorge — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_fortescue_falls_jubula',
                'name' => 'Fortescue Falls (Jubula)',
                'category' => 'parks',
                'latitude' => -22.4777579,
                'longitude' => 118.5506552,
                'address' => 'Dales Rd, Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Fortescue Falls (Jubula) — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_nganjarli_burrup_peninsula',
                'name' => 'Nganjarli - Burrup Peninsula',
                'category' => 'parks',
                'latitude' => -20.6359169,
                'longitude' => 116.7875862,
                'address' => 'Burrup Road, Burrup WA 6713, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Nganjarli - Burrup Peninsula — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_kalamina_gorge',
                'name' => 'Kalamina Gorge',
                'category' => 'scenic',
                'latitude' => -22.4166789,
                'longitude' => 118.4030006,
                'address' => 'Kalamina Rd, Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Kalamina Gorge — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_mount_augustus_national_park',
                'name' => 'Mount Augustus National Park',
                'category' => 'parks',
                'latitude' => -24.28377,
                'longitude' => 116.814221,
                'address' => 'Mount Augustus Rd, East Lyons River WA 6705, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Mount Augustus National Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_hearson_s_cove',
                'name' => 'Hearson\'s Cove',
                'category' => 'scenic',
                'latitude' => -20.6305556,
                'longitude' => 116.7972222,
                'address' => 'Hearson\\\'s Cove, Burrup WA 6714, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Hearson\'s Cove — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_joffre_falls_lookout',
                'name' => 'Joffre Falls Lookout',
                'category' => 'scenic',
                'latitude' => -22.3907536,
                'longitude' => 118.269036,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Joffre Falls Lookout — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_dales_gorge',
                'name' => 'Dales Gorge',
                'category' => 'parks',
                'latitude' => -22.4924358,
                'longitude' => 118.5203228,
                'address' => 'Dales Rd, Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Dales Gorge — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_python_pool',
                'name' => 'Python Pool',
                'category' => 'scenic',
                'latitude' => -21.3337056,
                'longitude' => 117.2383056,
                'address' => 'Millstream WA 6716, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Python Pool — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_horseshoe_gorge',
                'name' => 'Horseshoe Gorge',
                'category' => 'scenic',
                'latitude' => -21.3322081,
                'longitude' => 117.072273,
                'address' => 'Warlu Rd, Millstream WA 6716, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Horseshoe Gorge — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_mauritius_beach',
                'name' => 'Mauritius Beach',
                'category' => 'scenic',
                'latitude' => -21.8092316,
                'longitude' => 114.0951134,
                'address' => 'Yardie Creek Rd, Exmouth WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Mauritius Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_bundegi_beach',
                'name' => 'Bundegi Beach',
                'category' => 'scenic',
                'latitude' => -21.8265229,
                'longitude' => 114.1777657,
                'address' => 'Learmonth Minilya Rd, North West Cape WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Bundegi Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_sandy_bay',
                'name' => 'Sandy bay',
                'category' => 'scenic',
                'latitude' => -22.2318237,
                'longitude' => 113.8427169,
                'address' => 'Sandy bay, Cape Range National Park WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Sandy bay — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_town_beach',
                'name' => 'Town Beach',
                'category' => 'scenic',
                'latitude' => -21.9518895,
                'longitude' => 114.138919,
                'address' => 'Town Beach, Exmouth WA, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Town Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_pebble_beach',
                'name' => 'Pebble Beach',
                'category' => 'scenic',
                'latitude' => -22.0358265,
                'longitude' => 114.1151369,
                'address' => 'Pebble Beach, North West Cape WA, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Pebble Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_jims_beach',
                'name' => 'Jims Beach',
                'category' => 'scenic',
                'latitude' => -21.8154352,
                'longitude' => 114.0805764,
                'address' => 'Jims Beach, North West Cape WA, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Jims Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_dunes_beach',
                'name' => 'Dunes Beach',
                'category' => 'scenic',
                'latitude' => -21.8014366,
                'longitude' => 114.1393833,
                'address' => 'North West Cape WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Dunes Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_oyster_stacks_snorkelling_area',
                'name' => 'Oyster Stacks Snorkelling Area',
                'category' => 'scenic',
                'latitude' => -22.1325,
                'longitude' => 113.8769444,
                'address' => 'Cape Range National Park WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Oyster Stacks Snorkelling Area — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_tank_hill_lookout',
                'name' => 'Tank Hill Lookout',
                'category' => 'scenic',
                'latitude' => -21.176063,
                'longitude' => 119.7431381,
                'address' => 'Marble Bar WA 6760, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Tank Hill Lookout — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_karratha_lookout',
                'name' => 'Karratha Lookout',
                'category' => 'scenic',
                'latitude' => -20.7355389,
                'longitude' => 116.8589814,
                'address' => 'Mulataga WA 6714, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Karratha Lookout — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_radio_hill_lookout_newman',
                'name' => 'Radio Hill Lookout Newman',
                'category' => 'parks',
                'latitude' => -23.3628832,
                'longitude' => 119.7258667,
                'address' => 'LOT 1508 Howard Cl, Newman WA 6753, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Radio Hill Lookout Newman — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_mount_herbert_lookout',
                'name' => 'Mount Herbert Lookout',
                'category' => 'scenic',
                'latitude' => -21.3255101,
                'longitude' => 117.2164976,
                'address' => 'Roebourne-Wittenoom Rd, Millstream WA 6716, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Mount Herbert Lookout — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_lookout_rocks',
                'name' => 'Lookout Rocks',
                'category' => 'scenic',
                'latitude' => -21.95,
                'longitude' => 121.4,
                'address' => 'Lookout Rocks, Nullagine WA 6758, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lookout Rocks — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_yaburara_heritage_trail',
                'name' => 'Yaburara Heritage Trail',
                'category' => 'parks',
                'latitude' => -20.7412626,
                'longitude' => 116.8448764,
                'address' => 'Stove Hill WA 6714, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Yaburara Heritage Trail — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_sunrise_beach',
                'name' => 'Sunrise Beach',
                'category' => 'scenic',
                'latitude' => -21.9535132,
                'longitude' => 114.1394907,
                'address' => '91 Madaffari Dr, Exmouth WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Sunrise Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_exmouth_harbour',
                'name' => 'exmouth harbour',
                'category' => 'scenic',
                'latitude' => -21.9323088,
                'longitude' => 114.1278654,
                'address' => 'Exmouth WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'exmouth harbour — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_vlamingh_head_lighthouse',
                'name' => 'Vlamingh Head Lighthouse',
                'category' => 'scenic',
                'latitude' => -21.8083335,
                'longitude' => 114.1103088,
                'address' => 'Lot 2 Yardie Creek Rd, North West Cape WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Vlamingh Head Lighthouse — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_charles_knife_canyon',
                'name' => 'Charles Knife Canyon',
                'category' => 'scenic',
                'latitude' => -22.1087236,
                'longitude' => 114.0285079,
                'address' => 'Charles Knife Rd, Learmonth WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Charles Knife Canyon — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_shothole_canyon',
                'name' => 'Shothole Canyon',
                'category' => 'scenic',
                'latitude' => -22.065114,
                'longitude' => 114.0107479,
                'address' => 'Shothole Canyon Rd, North West Cape WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Shothole Canyon — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_fern_pool',
                'name' => 'Fern Pool',
                'category' => 'scenic',
                'latitude' => -22.4775889,
                'longitude' => 118.5482217,
                'address' => 'Dales Rd, Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Fern Pool — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_karijini_experience',
                'name' => 'Karijini Experience',
                'category' => 'scenic',
                'latitude' => -22.485877,
                'longitude' => 118.463478,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Karijini Experience — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_turquoise_bay',
                'name' => 'Turquoise Bay',
                'category' => 'scenic',
                'latitude' => -22.0978565,
                'longitude' => 113.8881097,
                'address' => 'Turquoise Bay, Cape Range National Park WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => true,
                'description' => 'Turquoise Bay — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_lakeside_snorkelling_area',
                'name' => 'Lakeside Snorkelling Area',
                'category' => 'scenic',
                'latitude' => -22.0342363,
                'longitude' => 113.9162691,
                'address' => 'Cape Range National Park WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lakeside Snorkelling Area — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_mangrove_bay',
                'name' => 'Mangrove Bay',
                'category' => 'scenic',
                'latitude' => -21.9656186,
                'longitude' => 113.9433037,
                'address' => 'Exmouth WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Mangrove Bay — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_pretty_pool_park',
                'name' => 'Pretty Pool Park',
                'category' => 'parks',
                'latitude' => -20.3160017,
                'longitude' => 118.6429352,
                'address' => '34 Matheson Dr, Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Pretty Pool Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_marapikurrinya_park',
                'name' => 'Marapikurrinya Park',
                'category' => 'parks',
                'latitude' => -20.3109917,
                'longitude' => 118.5750116,
                'address' => '4 Richardson St, Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Marapikurrinya Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_cemetery_beach_park',
                'name' => 'Cemetery Beach Park',
                'category' => 'parks',
                'latitude' => -20.3080556,
                'longitude' => 118.6055556,
                'address' => 'Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Cemetery Beach Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_redbank_bridge_lookout_dampier_salt',
                'name' => 'Redbank Bridge Lookout - Dampier Salt',
                'category' => 'scenic',
                'latitude' => -20.344736,
                'longitude' => 118.6311258,
                'address' => 'Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Redbank Bridge Lookout - Dampier Salt — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_dalgety_house_museum',
                'name' => 'Dalgety House Museum',
                'category' => 'scenic',
                'latitude' => -20.3133362,
                'longitude' => 118.5767979,
                'address' => 'LOT 462 Anderson St, Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Dalgety House Museum — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_4_mile_beach_4wd_access',
                'name' => '4 Mile Beach 4wd Access',
                'category' => 'scenic',
                'latitude' => -20.3224953,
                'longitude' => 118.6433583,
                'address' => '30 Dowding Wy, Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => '4 Mile Beach 4wd Access — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_port_hedland_beach',
                'name' => 'Port Hedland Beach',
                'category' => 'parks',
                'latitude' => -20.3056694,
                'longitude' => 118.6170077,
                'address' => '69/70 Sutherland St, Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Port Hedland Beach — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_lions_club_park',
                'name' => 'Lions Club Park',
                'category' => 'parks',
                'latitude' => -20.3106747,
                'longitude' => 118.5832195,
                'address' => '15 Morgans St, Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lions Club Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_war_memorial',
                'name' => 'War Memorial',
                'category' => 'parks',
                'latitude' => -20.3140586,
                'longitude' => 118.5758307,
                'address' => 'Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'War Memorial — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_6_mile_creek',
                'name' => '6 mile creek',
                'category' => 'parks',
                'latitude' => -20.3254101,
                'longitude' => 118.6668813,
                'address' => 'Gray St, Port Hedland WA 6721, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => '6 mile creek — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_koombana_park',
                'name' => 'Koombana Park',
                'category' => 'parks',
                'latitude' => -20.4200706,
                'longitude' => 118.6093771,
                'address' => '47 Steamer Ave, South Hedland WA 6722, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Koombana Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_red_dog_memorial_statue_dampier_western_australi',
                'name' => 'Red Dog Memorial Statue, Dampier, Western Australia',
                'category' => 'scenic',
                'latitude' => -20.6641795,
                'longitude' => 116.7175075,
                'address' => 'LOT 397 Central Ave, Dampier WA 6713, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Red Dog Memorial Statue, Dampier, Western Australia — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_kings_beach',
                'name' => 'Kings Beach',
                'category' => 'scenic',
                'latitude' => -20.6230718,
                'longitude' => 116.8056355,
                'address' => 'Burrup WA 6714, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Kings Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_norbill_bay',
                'name' => 'Norbill bay',
                'category' => 'scenic',
                'latitude' => -20.4782614,
                'longitude' => 116.609044,
                'address' => 'Dampier Archipelago WA 6713, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Norbill bay — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_aremvee_beach',
                'name' => 'Aremvee Beach',
                'category' => 'scenic',
                'latitude' => -20.538797,
                'longitude' => 116.805738,
                'address' => 'Unnamed Road, Burrup WA 6714, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Aremvee Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_walgu_park',
                'name' => 'Walgu park',
                'category' => 'parks',
                'latitude' => -20.7366279,
                'longitude' => 116.8451176,
                'address' => '66 Welcome Rd, Karratha WA 6714, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Walgu park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_cossack_historic_town',
                'name' => 'Cossack Historic Town',
                'category' => 'scenic',
                'latitude' => -20.6788862,
                'longitude' => 117.1890264,
                'address' => 'Pearl St, Cossack WA 6720, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Cossack Historic Town — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_lion_park',
                'name' => 'Lion Park',
                'category' => 'parks',
                'latitude' => -20.6630371,
                'longitude' => 116.71677,
                'address' => 'Dampier WA 6713, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Lion Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_kalamina_falls',
                'name' => 'Kalamina Falls',
                'category' => 'scenic',
                'latitude' => -22.4173246,
                'longitude' => 118.4022185,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Kalamina Falls — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_eagle_rock_falls',
                'name' => 'Eagle Rock Falls',
                'category' => 'scenic',
                'latitude' => -23.086311,
                'longitude' => 119.582208,
                'address' => 'Unnamed Road, Newman WA 6753, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Eagle Rock Falls — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_handrail_pool',
                'name' => 'Handrail Pool',
                'category' => 'scenic',
                'latitude' => -22.3594116,
                'longitude' => 118.2891029,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Handrail Pool — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_gordon_falls',
                'name' => 'Gordon Falls',
                'category' => 'scenic',
                'latitude' => -22.4848647,
                'longitude' => 118.5707746,
                'address' => 'Gordon Falls, Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Gordon Falls — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_three_pools',
                'name' => 'Three Pools',
                'category' => 'scenic',
                'latitude' => -23.1338611,
                'longitude' => 119.699671,
                'address' => 'Newman WA 6753, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Three Pools — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_red_dog_gorge',
                'name' => 'Red Dog Gorge',
                'category' => 'parks',
                'latitude' => -21.2869939,
                'longitude' => 117.0675331,
                'address' => 'Warlu Rd, Millstream WA 6716, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Red Dog Gorge — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_kalgan_pool',
                'name' => 'Kalgan Pool',
                'category' => 'scenic',
                'latitude' => -23.1879224,
                'longitude' => 119.6995083,
                'address' => 'Newman WA 6753, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Kalgan Pool — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_kermits_pool',
                'name' => 'Kermits Pool',
                'category' => 'scenic',
                'latitude' => -22.360016,
                'longitude' => 118.2868685,
                'address' => 'Weano Rd, Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'Kermits Pool — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_kialrah_pool',
                'name' => 'Kialrah Pool',
                'category' => 'scenic',
                'latitude' => -20.9833333,
                'longitude' => 117.4,
                'address' => 'Kialrah Pool, Sherlock WA 6714, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Kialrah Pool — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_turquoise_bay_drift_snorkel',
                'name' => 'Turquoise Bay Drift Snorkel',
                'category' => 'scenic',
                'latitude' => -22.099909,
                'longitude' => 113.885307,
                'address' => 'WV2P+24, Cape Range National Park WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Turquoise Bay Drift Snorkel — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_ningaloo_coast',
                'name' => 'Ningaloo Coast',
                'category' => 'scenic',
                'latitude' => -22.704723,
                'longitude' => 113.6754832,
                'address' => 'Ningaloo WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Ningaloo Coast — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_osprey_bay_snorkeling',
                'name' => 'Osprey Bay Snorkeling',
                'category' => 'scenic',
                'latitude' => -22.237303,
                'longitude' => 113.839528,
                'address' => 'Osprey Bay campground, Yardie Creek Rd, Cape Range National Park WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Osprey Bay Snorkeling — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_five_fingers_reef',
                'name' => 'Five Fingers Reef',
                'category' => 'scenic',
                'latitude' => -23.1797459,
                'longitude' => 113.7657069,
                'address' => 'Unnamed Road, Lyndon WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Five Fingers Reef — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_bill_s_bay',
                'name' => 'Bill\'s Bay',
                'category' => 'scenic',
                'latitude' => -23.1424321,
                'longitude' => 113.7692174,
                'address' => 'Coral Bay WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Bill\'s Bay — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_paradise_beach',
                'name' => 'Paradise Beach',
                'category' => 'scenic',
                'latitude' => -23.1460961,
                'longitude' => 113.7669428,
                'address' => 'Lyndon WA 6701, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Paradise Beach — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_historic_jetty',
                'name' => 'Historic jetty',
                'category' => 'scenic',
                'latitude' => -20.6321423,
                'longitude' => 117.1981848,
                'address' => '18 Miller Cl, Point Samson WA 6720, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Historic jetty — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_paraburdoo_resilience_sculpture',
                'name' => 'Paraburdoo Resilience Sculpture',
                'category' => 'scenic',
                'latitude' => -23.2015208,
                'longitude' => 117.6829154,
                'address' => 'Paraburdoo WA 6754, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Paraburdoo Resilience Sculpture — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_tom_price_visitor_information_bay',
                'name' => 'Tom Price Visitor Information Bay',
                'category' => 'scenic',
                'latitude' => -22.698119,
                'longitude' => 117.7868063,
                'address' => '8Q2P+QP, Tom Price WA 6751, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Tom Price Visitor Information Bay — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_doug_talbot_memorial_park',
                'name' => 'Doug Talbot Memorial Park',
                'category' => 'parks',
                'latitude' => -22.6944563,
                'longitude' => 117.7944864,
                'address' => '25b old, Mine Rd, Tom Price WA 6751, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Doug Talbot Memorial Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_grassy_knoll_tom_price',
                'name' => 'Grassy Knoll (Tom Price)',
                'category' => 'scenic',
                'latitude' => -22.6915054,
                'longitude' => 117.7858436,
                'address' => 'Tom Price WA 6751, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Grassy Knoll (Tom Price) — a striking corner of the Pilbara coast and ranges, where turquoise water or ancient red stone steals the show.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_pil_tom_price_pump_track',
                'name' => 'Tom Price Pump Track',
                'category' => 'parks',
                'latitude' => -22.6883434,
                'longitude' => 117.7918927,
                'address' => 'Tom Price WA 6751, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Tom Price Pump Track — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_kings_lake',
                'name' => 'Kings lake',
                'category' => 'parks',
                'latitude' => -22.6870074,
                'longitude' => 117.7612963,
                'address' => '8Q76+5G, Tom Price WA 6751, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Kings lake — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_tom_price_dog_park',
                'name' => 'Tom Price Dog Park',
                'category' => 'parks',
                'latitude' => -22.687943,
                'longitude' => 117.7918055,
                'address' => 'North Rd, Tom Price WA 6751, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Tom Price Dog Park — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_hilary_paull',
                'name' => 'Hilary Paull',
                'category' => 'parks',
                'latitude' => -22.6883506,
                'longitude' => 117.7612577,
                'address' => 'Kings lake, Tom Price WA 6751, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Hilary Paull — a wild Pilbara reserve of red rock, deep gorges and rare desert life. Remote, raw and unforgettable.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_pil_mutts_cafe_restaurant_in_exmouth',
                'name' => 'Mutts Cafe & Restaurant in Exmouth',
                'category' => 'food',
                'latitude' => -21.9387805,
                'longitude' => 114.1299795,
                'address' => '1 Pellew St, Exmouth WA 6707, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Mutts Cafe & Restaurant in Exmouth — a welcome outback refuel stop serving good coffee and hearty fare between the region\'s epic landscapes.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_pil_froth_craft_brewery_exmouth_restaurant_entertain',
                'name' => 'Froth Craft Brewery Exmouth / Restaurant / Entertainment Venue',
                'category' => 'food',
                'latitude' => -21.9309,
                'longitude' => 114.12215,
                'address' => '5 Kennedy St, Exmouth WA 6707, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Froth Craft Brewery Exmouth / Restaurant / Entertainment Venue — a welcome outback refuel stop serving good coffee and hearty fare between the region\'s epic landscapes.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_pil_earlybird_cafe',
                'name' => 'Earlybird Cafe',
                'category' => 'food',
                'latitude' => -21.930675,
                'longitude' => 114.1222713,
                'address' => '3 Kennedy St, Exmouth WA 6707, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Earlybird Cafe — a welcome outback refuel stop serving good coffee and hearty fare between the region\'s epic landscapes.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_pil_whalers_restaurant',
                'name' => 'Whalers Restaurant',
                'category' => 'food',
                'latitude' => -21.9454083,
                'longitude' => 114.1320842,
                'address' => '2 Murat Rd, Exmouth WA 6707, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Whalers Restaurant — a welcome outback refuel stop serving good coffee and hearty fare between the region\'s epic landscapes.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_pil_karma_kitchen',
                'name' => 'Karma Kitchen',
                'category' => 'food',
                'latitude' => -21.9367678,
                'longitude' => 114.1305279,
                'address' => '2 Truscott Cres, Exmouth WA 6707, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Karma Kitchen — a welcome outback refuel stop serving good coffee and hearty fare between the region\'s epic landscapes.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_pil_bamboo_sushi_coffee_juice_hot_food',
                'name' => 'Bamboo -Sushi | Coffee | Juice | Hot Food',
                'category' => 'food',
                'latitude' => -21.9312848,
                'longitude' => 114.1229551,
                'address' => '37 Maidstone Cres, Exmouth WA 6707, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Bamboo -Sushi | Coffee | Juice | Hot Food — a welcome outback refuel stop serving good coffee and hearty fare between the region\'s epic landscapes.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
        ];

        foreach ($locations as $data) {
            // points drives tier via the model's saving() hook; use the per-tier
            // default so the explicit tier and the derived tier agree.
            $data['points'] = Location::defaultPointsForTier($data['tier']);

            Location::updateOrCreate(
                ['name' => $data['name']],
                array_merge($data, [
                    'verification_tags' => [],
                    'active' => true,
                    'status' => Location::STATUS_APPROVED,
                    'submitted_by' => null,
                ])
            );
        }
    }
}
