<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class WaBulkSouthWestSeeder extends Seeder
{
    /**
     * Bulk REAL public locations for the South West WA region — Margaret River,
     * Busselton, Dunsborough, Bunbury, Augusta capes & caves and the surrounding
     * Leeuwin-Naturaliste coast/forest. Sourced from the Google Places API (New)
     * Text Search and deduped by Places id, then by name/slug.
     *
     * Idempotent: keyed on `name` via updateOrCreate (the slug column is unique
     * and required, so it is always supplied in the attributes). points is set
     * from defaultPointsForTier(tier); the Location model's saving() hook then
     * re-derives tier from points so the two stay consistent. updateOrCreate
     * runs save() so that hook fires.
     */
    public function run(): void
    {
        $locations = [
            [
                'slug' => 'sw_leeuwin_naturaliste_national_park',
                'name' => 'Leeuwin-Naturaliste National Park',
                'category' => 'parks',
                'latitude' => -33.539165,
                'longitude' => 115.0272203,
                'address' => 'Cape Naturaliste Rd, Dunsborough WA 6281, Australia',
                'tier' => 4,
                'is_major_destination' => true,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_wooditjup_national_park',
                'name' => 'Wooditjup National Park',
                'category' => 'parks',
                'latitude' => -33.9343121,
                'longitude' => 115.0684782,
                'address' => 'Carters Rd, Margaret River WA 6285, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_tuart_forest_national_park',
                'name' => 'Tuart Forest National Park',
                'category' => 'parks',
                'latitude' => -33.5547952,
                'longitude' => 115.5144431,
                'address' => 'Higgins Rd, Capel WA 6271, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_meelup_regional_park',
                'name' => 'Meelup Regional Park',
                'category' => 'parks',
                'latitude' => -33.5812867,
                'longitude' => 115.0851494,
                'address' => 'Meelup Beach Rd, Dunsborough WA 6280, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_jewel_cave',
                'name' => 'Jewel Cave',
                'category' => 'parks',
                'latitude' => -34.2738174,
                'longitude' => 115.0984017,
                'address' => 'Jewel Caves Rd, Deepdene WA 6290, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_wellington_national_park',
                'name' => 'Wellington National Park',
                'category' => 'parks',
                'latitude' => -33.320545,
                'longitude' => 115.980291,
                'address' => 'Coalfields Rd, Worsley WA 6225, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_wiltshire_butler_national_park',
                'name' => 'Wiltshire Butler National Park',
                'category' => 'parks',
                'latitude' => -34.0242465,
                'longitude' => 115.4852012,
                'address' => 'Schroeder WA 6285, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_yelverton_national_park',
                'name' => 'Yelverton National Park',
                'category' => 'parks',
                'latitude' => -33.7371515,
                'longitude' => 115.0910798,
                'address' => 'Yelverton WA 6280, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_boranup_forest',
                'name' => 'Boranup Forest',
                'category' => 'parks',
                'latitude' => -34.1295121,
                'longitude' => 115.0762536,
                'address' => 'Boranup WA 6286, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_whicher_national_park',
                'name' => 'Whicher National Park',
                'category' => 'parks',
                'latitude' => -33.7739737,
                'longitude' => 115.4852012,
                'address' => 'Yoganup WA 6275, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_hilliger_national_park',
                'name' => 'Hilliger National Park',
                'category' => 'parks',
                'latitude' => -34.2383403,
                'longitude' => 115.6712871,
                'address' => 'Stewart Rd, Darradup WA 6275, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_gloucester_national_park',
                'name' => 'Gloucester National Park',
                'category' => 'parks',
                'latitude' => -34.4504157,
                'longitude' => 116.0548749,
                'address' => 'Burma Rd, Pemberton WA 6260, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_heartbreak_trail',
                'name' => 'Heartbreak Trail',
                'category' => 'parks',
                'latitude' => -34.4904653,
                'longitude' => 115.9518618,
                'address' => 'Heart Break Trail, Yeagarup WA 6260, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_greater_beedelup_national_park',
                'name' => 'Greater Beedelup National Park',
                'category' => 'parks',
                'latitude' => -34.382614,
                'longitude' => 115.798655,
                'address' => 'Reeve Rd, Beedelup WA 6260, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_blackwood_river_national_park',
                'name' => 'Blackwood River National Park',
                'category' => 'parks',
                'latitude' => -34.0825876,
                'longitude' => 115.4015406,
                'address' => 'Sues Rd, Darradup WA 6275, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_capes_raptor_centre',
                'name' => 'Capes Raptor Centre',
                'category' => 'parks',
                'latitude' => -33.984719,
                'longitude' => 115.055072,
                'address' => '341 Boodjidup Rd, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_margaret_river_mouth_viewpoint',
                'name' => 'Margaret River Mouth Viewpoint',
                'category' => 'scenic',
                'latitude' => -33.9714916,
                'longitude' => 114.9871752,
                'address' => 'Wallcliffe Rd, Margaret River WA 628, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_leeuwin_naturaliste_national_park_2',
                'name' => 'Leeuwin - Naturaliste National Park',
                'category' => 'parks',
                'latitude' => -33.9402233,
                'longitude' => 115.004335,
                'address' => '3253+WP, Yebble WA 6285, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_gnarabup_lookout',
                'name' => 'Gnarabup Lookout',
                'category' => 'scenic',
                'latitude' => -33.9910206,
                'longitude' => 114.9898386,
                'address' => 'Ocean View Rd, Gnarabup WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_scott_national_park',
                'name' => 'Scott National Park',
                'category' => 'parks',
                'latitude' => -34.2580979,
                'longitude' => 115.2355443,
                'address' => 'Scott River WA 6288, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_hawke_national_park',
                'name' => 'Hawke National Park',
                'category' => 'parks',
                'latitude' => -34.518038,
                'longitude' => 115.8707401,
                'address' => 'Lake Rd, Yeagarup WA 6260, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_dalgarup_national_park',
                'name' => 'Dalgarup National Park',
                'category' => 'parks',
                'latitude' => -33.985091,
                'longitude' => 115.9767688,
                'address' => 'Acacia Rd, Maranup WA 6256, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_forest_grove_national_park',
                'name' => 'Forest Grove National Park',
                'category' => 'parks',
                'latitude' => -34.079883,
                'longitude' => 115.126584,
                'address' => 'Furniss Rd, Forest Grove WA 6286, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_busselton_jetty',
                'name' => 'Busselton Jetty',
                'category' => 'scenic',
                'latitude' => -33.6445312,
                'longitude' => 115.3450351,
                'address' => '17 Foreshore Parade, Busselton WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => true,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_milyeannup_national_park',
                'name' => 'Milyeannup National Park',
                'category' => 'parks',
                'latitude' => -34.1668999,
                'longitude' => 115.6391526,
                'address' => 'Darradup WA 6275, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_kevill_road_waterfall',
                'name' => 'Kevill Road Waterfall',
                'category' => 'scenic',
                'latitude' => -33.9418928,
                'longitude' => 115.0392334,
                'address' => 'Margaret River WA 6285, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_leeuwin_naturalists_national_park',
                'name' => 'Leeuwin naturalists national park',
                'category' => 'parks',
                'latitude' => -33.9535468,
                'longitude' => 115.0629667,
                'address' => 'Margaret River WA 6285, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'sw_sugarloaf_rock',
                'name' => 'Sugarloaf Rock',
                'category' => 'scenic',
                'latitude' => -33.5593756,
                'longitude' => 115.0051128,
                'address' => 'Sugarloaf Rd, Naturaliste WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_rotary_park',
                'name' => 'Rotary Park',
                'category' => 'parks',
                'latitude' => -33.9444758,
                'longitude' => 115.0740188,
                'address' => '53/69 Bussell Hwy, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_busselton_underwater_observatory',
                'name' => 'Busselton Underwater Observatory',
                'category' => 'scenic',
                'latitude' => -33.6300064,
                'longitude' => 115.3385727,
                'address' => '989Q+XC, West Busselton WA 6280, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_conto_campground',
                'name' => 'Conto Campground',
                'category' => 'parks',
                'latitude' => -34.0790567,
                'longitude' => 115.0176002,
                'address' => 'Conto Rd, Boranup WA 6286, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_bunbury_wildlife_park',
                'name' => 'Bunbury Wildlife Park',
                'category' => 'parks',
                'latitude' => -33.3423642,
                'longitude' => 115.6301016,
                'address' => '7 Prince Philip Dr, South Bunbury WA 6230, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_ambergate_reserve',
                'name' => 'Ambergate Reserve',
                'category' => 'parks',
                'latitude' => -33.736672,
                'longitude' => 115.3263788,
                'address' => '988 Queen Elizabeth Ave, Chapman Hill WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_wooditjup_mountain_bike_and_walk_trail_head',
                'name' => 'Wooditjup Mountain Bike and Walk Trail Head',
                'category' => 'parks',
                'latitude' => -33.9341021,
                'longitude' => 115.0683194,
                'address' => 'Wadandi Track, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_castle_rock',
                'name' => 'Castle Rock',
                'category' => 'scenic',
                'latitude' => -33.5833201,
                'longitude' => 115.0998276,
                'address' => 'Castle Rock Rd, Dunsborough WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_black_point',
                'name' => 'Black Point',
                'category' => 'parks',
                'latitude' => -34.4173992,
                'longitude' => 115.5432411,
                'address' => 'Black Point Rd, Lake Jasper WA 6260, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_possum_spotlighting_trail',
                'name' => 'Possum Spotlighting Trail',
                'category' => 'parks',
                'latitude' => -33.6316562,
                'longitude' => 115.4302168,
                'address' => 'Layman Rd, Wonnerup WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_three_bears',
                'name' => 'Three Bears',
                'category' => 'scenic',
                'latitude' => -33.5806846,
                'longitude' => 115.014183,
                'address' => 'Cape to Cape Walk Track, Naturaliste WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_cape2camp',
                'name' => 'Cape2Camp',
                'category' => 'parks',
                'latitude' => -33.9559178,
                'longitude' => 115.0766087,
                'address' => '3 Walkington Ave, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_blackhurst_park',
                'name' => 'Blackhurst Park',
                'category' => 'parks',
                'latitude' => -33.6015557,
                'longitude' => 115.1048199,
                'address' => '60 Bay View Cres, Dunsborough WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_hamelin_bay_beach',
                'name' => 'Hamelin Bay Beach',
                'category' => 'scenic',
                'latitude' => -34.21964,
                'longitude' => 115.0309284,
                'address' => 'Hamelin Bay Beach, Cape to Cape Walk Track, Boranup WA 6286, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_shelley_cove',
                'name' => 'Shelley Cove',
                'category' => 'scenic',
                'latitude' => -33.5372293,
                'longitude' => 115.0316154,
                'address' => 'Shelley Cove, 86 Bunker Bay Rd, Naturaliste WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_redgate_beach',
                'name' => 'Redgate Beach',
                'category' => 'scenic',
                'latitude' => -34.0391747,
                'longitude' => 114.998537,
                'address' => 'Redgate Beach, Redgate Rd, Redgate WA 6286, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_granny_s_pool',
                'name' => 'Granny\'s Pool',
                'category' => 'scenic',
                'latitude' => -34.3452753,
                'longitude' => 115.1696402,
                'address' => 'Augusta WA 6290, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_honeycombs_beach',
                'name' => 'Honeycombs Beach',
                'category' => 'scenic',
                'latitude' => -33.7724427,
                'longitude' => 114.9926231,
                'address' => 'Busselton WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_gnarabup_beach',
                'name' => 'Gnarabup Beach',
                'category' => 'scenic',
                'latitude' => -33.9899037,
                'longitude' => 114.99129,
                'address' => 'Gnarabup Rd, Gnarabup WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_meelup_beach',
                'name' => 'Meelup Beach',
                'category' => 'scenic',
                'latitude' => -33.5732487,
                'longitude' => 115.0870954,
                'address' => 'Meelup Beach, Western Australia 6281, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_yallingup_lagoon',
                'name' => 'Yallingup Lagoon',
                'category' => 'parks',
                'latitude' => -33.6400575,
                'longitude' => 115.0235681,
                'address' => 'Yallingup Beach Rd, Yallingup WA 6282, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_white_elephant_cafe_margaret_river',
                'name' => 'White Elephant Cafe - Margaret River',
                'category' => 'food',
                'latitude' => -33.9906406,
                'longitude' => 114.9912133,
                'address' => '1 Gnarabup Rd, Gnarabup WA 6285, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A local South West WA favourite for a relaxed bite or coffee between coast and forest.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_boranup_beach',
                'name' => 'Boranup Beach',
                'category' => 'scenic',
                'latitude' => -34.1706493,
                'longitude' => 115.0315855,
                'address' => 'Boranup Beach, Boranup WA, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_kilcarnup_beach',
                'name' => 'Kilcarnup Beach',
                'category' => 'scenic',
                'latitude' => -33.9468502,
                'longitude' => 114.9926582,
                'address' => 'Kilcarnup Beach, Yebble WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_kabbijgup_beach',
                'name' => 'Kabbijgup Beach',
                'category' => 'scenic',
                'latitude' => -33.5833648,
                'longitude' => 115.0142541,
                'address' => 'Kabbijgup Beach, Western Australia, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_point_picquet',
                'name' => 'Point Picquet',
                'category' => 'scenic',
                'latitude' => -33.5656301,
                'longitude' => 115.0841837,
                'address' => 'Naturaliste WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_forrest_beach',
                'name' => 'Forrest Beach',
                'category' => 'scenic',
                'latitude' => -33.6105259,
                'longitude' => 115.4248567,
                'address' => 'Forrest Beach, Western Australia, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_north_point',
                'name' => 'North Point',
                'category' => 'scenic',
                'latitude' => -33.8590129,
                'longitude' => 114.9853976,
                'address' => 'Bay, Cowaramup WA 6284, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_peppermint_grove_beach',
                'name' => 'Peppermint Grove Beach',
                'category' => 'scenic',
                'latitude' => -33.5374181,
                'longitude' => 115.4950107,
                'address' => 'Peppermint Grove Beach, Western Australia, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_riflebutts_reserve',
                'name' => 'Riflebutts Reserve',
                'category' => 'parks',
                'latitude' => -33.9777536,
                'longitude' => 114.9903238,
                'address' => 'Ned Higgins Park, Surfers Point Rd, Prevelly WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_gas_bay',
                'name' => 'Gas Bay',
                'category' => 'scenic',
                'latitude' => -34.002605,
                'longitude' => 114.9978208,
                'address' => 'Gnarabup WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_busselton_foreshore',
                'name' => 'Busselton Foreshore',
                'category' => 'parks',
                'latitude' => -33.645071,
                'longitude' => 115.3450174,
                'address' => 'Queen St, Busselton WA 6280, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_hamelin_bay_observation_deck',
                'name' => 'Hamelin Bay Observation Deck',
                'category' => 'scenic',
                'latitude' => -34.2227117,
                'longitude' => 115.0253772,
                'address' => 'Hamelin Bay WA 6288, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_prevelly_rockpools',
                'name' => 'Prevelly Rockpools',
                'category' => 'scenic',
                'latitude' => -33.9726672,
                'longitude' => 114.9865486,
                'address' => 'Prevelly WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_margaret_river_tourist_park',
                'name' => 'Margaret River Tourist Park',
                'category' => 'parks',
                'latitude' => -33.9591708,
                'longitude' => 115.0692207,
                'address' => '44 Station Rd, Margaret River WA 6285, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_margaret_river_tuck_shop',
                'name' => 'Margaret River Tuck Shop',
                'category' => 'food',
                'latitude' => -33.9531347,
                'longitude' => 115.0736821,
                'address' => '147 Bussell Hwy, Margaret River WA 6285, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A local South West WA favourite for a relaxed bite or coffee between coast and forest.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_injidup_beach',
                'name' => 'Injidup Beach',
                'category' => 'scenic',
                'latitude' => -33.6990557,
                'longitude' => 114.9883973,
                'address' => 'Injidup Beach, lot 6282/LOT 10 Cape Clairault Rd, Yallingup WA 6282, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_dunsborough_beach',
                'name' => 'Dunsborough Beach',
                'category' => 'scenic',
                'latitude' => -33.6134695,
                'longitude' => 115.1111405,
                'address' => 'Dunsborough Beach, Western Australia 6281, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_canal_rocks',
                'name' => 'Canal Rocks',
                'category' => 'parks',
                'latitude' => -33.670172,
                'longitude' => 114.9951226,
                'address' => 'Leeuwin-Naturaliste National Park, Canal Rocks Rd, Busselton WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_smiths_beach',
                'name' => 'Smiths Beach',
                'category' => 'scenic',
                'latitude' => -33.6546841,
                'longitude' => 115.0204639,
                'address' => 'Smiths Beach, Western Australia, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_ngilgi_cave_ancient_lands_experience',
                'name' => 'Ngilgi Cave Ancient Lands Experience',
                'category' => 'scenic',
                'latitude' => -33.6420202,
                'longitude' => 115.0342884,
                'address' => '76 Yallingup Caves Rd, Yallingup WA 6282, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_yallingup_beach',
                'name' => 'Yallingup Beach',
                'category' => 'scenic',
                'latitude' => -33.6399764,
                'longitude' => 115.0243101,
                'address' => 'Yallingup Beach, Western Australia 6282, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_wonnerup_beach',
                'name' => 'Wonnerup Beach',
                'category' => 'scenic',
                'latitude' => -33.6163546,
                'longitude' => 115.4154152,
                'address' => 'Wonnerup Beach, Western Australia, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_little_meelup_beach',
                'name' => 'Little Meelup Beach',
                'category' => 'scenic',
                'latitude' => -33.5811952,
                'longitude' => 115.0950643,
                'address' => 'Little Meelup Beach, Western Australia 6281, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_barnard_park',
                'name' => 'Barnard Park',
                'category' => 'parks',
                'latitude' => -33.6446662,
                'longitude' => 115.3490352,
                'address' => 'Busselton WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_koombana_beach',
                'name' => 'Koombana Beach',
                'category' => 'scenic',
                'latitude' => -33.3196857,
                'longitude' => 115.6453187,
                'address' => 'Bunbury WA 6230, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_big4_breeze_holiday_parks_busselton',
                'name' => 'BIG4 Breeze Holiday Parks - Busselton',
                'category' => 'parks',
                'latitude' => -33.6562135,
                'longitude' => 115.307536,
                'address' => '10 Earnshaw Rd, West Busselton WA 6280, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_wallcliffe_road_lookout',
                'name' => 'Wallcliffe Road Lookout',
                'category' => 'scenic',
                'latitude' => -33.9728943,
                'longitude' => 114.9966789,
                'address' => '752 Wallcliffe Rd, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_hillview_road_lookout',
                'name' => 'Hillview Road Lookout',
                'category' => 'scenic',
                'latitude' => -34.298273,
                'longitude' => 115.09735,
                'address' => '757 Hillview Rd, Augusta WA 6290, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_cape_leeuwin_lighthouse',
                'name' => 'Cape Leeuwin Lighthouse',
                'category' => 'scenic',
                'latitude' => -34.3749541,
                'longitude' => 115.1363477,
                'address' => 'Leeuwin Rd, Augusta WA 6290, Australia',
                'tier' => 3,
                'is_major_destination' => true,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_lovers_bench',
                'name' => 'Lovers\' bench',
                'category' => 'scenic',
                'latitude' => -33.9444714,
                'longitude' => 115.077171,
                'address' => '334G+7Q, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_margaret_river_bananabout',
                'name' => 'Margaret River Bananabout',
                'category' => 'scenic',
                'latitude' => -33.9486055,
                'longitude' => 115.0742669,
                'address' => '97 Bussell Hwy, Margaret River WA 6285, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_memorial_park',
                'name' => 'Memorial Park',
                'category' => 'parks',
                'latitude' => -33.9508667,
                'longitude' => 115.0749186,
                'address' => '68 Willmott Ave, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_doust_s_corner',
                'name' => 'Doust\'s Corner',
                'category' => 'scenic',
                'latitude' => -33.973494,
                'longitude' => 115.0850625,
                'address' => '2 Andrews Way, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_cape_mentelle',
                'name' => 'Cape Mentelle',
                'category' => 'scenic',
                'latitude' => -33.9670545,
                'longitude' => 115.0373,
                'address' => '331 Wallcliffe Rd, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_margaret_river_farmers_market',
                'name' => 'Margaret River Farmers Market',
                'category' => 'food',
                'latitude' => -33.9576538,
                'longitude' => 115.0738372,
                'address' => 'Lot 272 Bussell Hwy, Margaret River WA 6285, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A local South West WA favourite for a relaxed bite or coffee between coast and forest.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_pre_historic_wombat_statue',
                'name' => 'Pre-Historic Wombat Statue',
                'category' => 'scenic',
                'latitude' => -33.9487746,
                'longitude' => 115.0740724,
                'address' => 'Bussell Hwy & Tunbridge St, 100 Bussell Hwy, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_lake_cave',
                'name' => 'Lake Cave',
                'category' => 'parks',
                'latitude' => -34.0790463,
                'longitude' => 115.0293094,
                'address' => 'Caves Rd &, Conto Rd, Forest Grove WA 6286, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_margaret_river_organic_garden_inc',
                'name' => 'Margaret River Organic Garden, Inc',
                'category' => 'parks',
                'latitude' => -33.9562244,
                'longitude' => 115.0740149,
                'address' => '171 Bussell Hwy, Margaret River WA 6285, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_joey_s_nose',
                'name' => 'Joey\'s Nose',
                'category' => 'scenic',
                'latitude' => -33.944778,
                'longitude' => 114.992467,
                'address' => '3X4R+3X, Yebble WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_nguraren_kalleep',
                'name' => 'Nguraren Kalleep',
                'category' => 'parks',
                'latitude' => -33.9435667,
                'longitude' => 115.0745882,
                'address' => 'Bussell Hwy, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_reuther_park',
                'name' => 'Reuther Park',
                'category' => 'parks',
                'latitude' => -33.9533166,
                'longitude' => 115.0731726,
                'address' => '2 Wallcliffe Rd, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_thomas_reserve',
                'name' => 'Thomas Reserve',
                'category' => 'parks',
                'latitude' => -33.9544365,
                'longitude' => 115.0910036,
                'address' => '47 Lantana Ln, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_river',
                'name' => 'River',
                'category' => 'parks',
                'latitude' => -33.9483599,
                'longitude' => 115.0823704,
                'address' => '332J+MW, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_mammoth_cave',
                'name' => 'Mammoth Cave',
                'category' => 'parks',
                'latitude' => -34.060037,
                'longitude' => 115.0296771,
                'address' => 'Caves Rd, Forest Grove WA 6286, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_kai_park',
                'name' => 'Kai Park',
                'category' => 'parks',
                'latitude' => -33.9544365,
                'longitude' => 115.0910036,
                'address' => '47 Lantana Ln, Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_giants_cave',
                'name' => 'Giants Cave',
                'category' => 'scenic',
                'latitude' => -34.0898166,
                'longitude' => 115.0437111,
                'address' => '7769 Caves Rd, Forest Grove WA 6286, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_hillier_drive_reserve',
                'name' => 'Hillier Drive Reserve',
                'category' => 'parks',
                'latitude' => -33.9563943,
                'longitude' => 115.0837773,
                'address' => 'Margaret River WA 6285, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_sand_walk',
                'name' => 'Sand Walk',
                'category' => 'scenic',
                'latitude' => -33.6173751,
                'longitude' => 115.1154582,
                'address' => '1879 Geographe Bay Rd, Dunsborough WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_the_mermaids_cave',
                'name' => 'The Mermaids Cave',
                'category' => 'scenic',
                'latitude' => -33.6496064,
                'longitude' => 115.3440747,
                'address' => '1/50 Queen St, Busselton WA 6280, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_cape_naturaliste_lighthouse',
                'name' => 'Cape Naturaliste Lighthouse',
                'category' => 'scenic',
                'latitude' => -33.537388,
                'longitude' => 115.018701,
                'address' => 'Leeuwin-Naturaliste National Park, 1267 Cape Naturaliste Rd, Naturaliste WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_gannet_rock',
                'name' => 'Gannet Rock',
                'category' => 'scenic',
                'latitude' => -33.568655,
                'longitude' => 115.0886526,
                'address' => 'Naturaliste WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_brennan_bay',
                'name' => 'Brennan Bay',
                'category' => 'scenic',
                'latitude' => -33.6565056,
                'longitude' => 115.248135,
                'address' => 'Busselton WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_hmas_swan',
                'name' => 'HMAS Swan',
                'category' => 'scenic',
                'latitude' => -33.5519167,
                'longitude' => 115.09935,
                'address' => 'HMAS Swan, Dunsborough WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_geographe_bay_margaret_st_groyne',
                'name' => 'Geographe Bay Margaret St Groyne',
                'category' => 'scenic',
                'latitude' => -33.651241,
                'longitude' => 115.3240959,
                'address' => 'West Busselton WA 6280, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'sw_blythe_reserve',
                'name' => 'Blythe Reserve',
                'category' => 'parks',
                'latitude' => -33.6041217,
                'longitude' => 115.1016452,
                'address' => 'Dunsborough WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_signal_park',
                'name' => 'Signal Park',
                'category' => 'parks',
                'latitude' => -33.6463727,
                'longitude' => 115.3424648,
                'address' => 'Busselton WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_vasse_lighthouse_site',
                'name' => 'Vasse lighthouse site',
                'category' => 'scenic',
                'latitude' => -33.6466102,
                'longitude' => 115.3436622,
                'address' => 'Queen St, Busselton WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_whale_watching_platform',
                'name' => 'Whale Watching Platform',
                'category' => 'scenic',
                'latitude' => -33.5331779,
                'longitude' => 115.0173068,
                'address' => 'Naturaliste WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_shelley_cove_lookout',
                'name' => 'Shelley Cove Lookout',
                'category' => 'scenic',
                'latitude' => -33.5359103,
                'longitude' => 115.0310457,
                'address' => 'Naturaliste WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_marri_conservation_reserve',
                'name' => 'Marri Conservation Reserve',
                'category' => 'parks',
                'latitude' => -33.609917,
                'longitude' => 115.1005294,
                'address' => '135-169 Naturaliste Terrace, Dunsborough WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_the_hockey_goal_statue',
                'name' => 'The Hockey Goal Statue',
                'category' => 'scenic',
                'latitude' => -33.6626241,
                'longitude' => 115.3574042,
                'address' => '98 Causeway Rd, Busselton WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_big_rock',
                'name' => 'Big Rock',
                'category' => 'scenic',
                'latitude' => -33.6261212,
                'longitude' => 115.0852592,
                'address' => 'End of, Big Rock Pl, Quedjinup WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_simmos_ice_creamery',
                'name' => 'Simmos Ice Creamery',
                'category' => 'parks',
                'latitude' => -33.6400222,
                'longitude' => 115.113,
                'address' => '161 Commonage Rd, Quindalup WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_vasse_river_delta_bird_hide',
                'name' => 'Vasse River Delta Bird Hide',
                'category' => 'parks',
                'latitude' => -33.6533495,
                'longitude' => 115.3532995,
                'address' => '12 Pioneer Cove, Busselton WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_captain_baudin_reserve',
                'name' => 'Captain Baudin Reserve',
                'category' => 'parks',
                'latitude' => -33.6253619,
                'longitude' => 115.4041653,
                'address' => 'Wonnerup WA 6280, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A protected slice of South West WA bushland — walk trails, towering forest and birdsong away from the crowds.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'sw_identity_sentinels',
                'name' => 'IDENTITY SENTINELS',
                'category' => 'scenic',
                'latitude' => -33.6061621,
                'longitude' => 115.1046855,
                'address' => 'Vincent St, Dunsborough WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'sw_windmills_lookout',
                'name' => 'Windmills Lookout',
                'category' => 'scenic',
                'latitude' => -33.5412664,
                'longitude' => 115.0091204,
                'address' => 'Naturaliste WA 6281, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A standout South West WA viewpoint where turquoise water, white sand and big coastal skies come together.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
        ];

        foreach ($locations as $data) {
            $data['points'] = Location::defaultPointsForTier($data['tier']);

            Location::updateOrCreate(
                ['name' => $data['name']],
                array_merge($data, [
                    'verification_tags' => [],
                    'active' => true,
                    'status' => Location::STATUS_APPROVED,
                    'submitted_by' => null,
                ])
            );
        }
    }
}
