<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Seeder;

class WaLocationsSeeder extends Seeder
{
    /**
     * A realistic, statewide set of REAL public locations across Western
     * Australia, sourced from the Google Places API (New) Text Search.
     * Idempotent: upserts by `slug` so re-running is safe.
     *
     * points drives tier in the admin, but here we set tier explicitly and let
     * points = defaultPointsForTier(tier). The Location model's saving() hook
     * then RE-derives tier from points (tierForPoints), and since points is the
     * tier default the two stay consistent. We call updateOrCreate (which runs
     * save()) so that hook fires.
     */
    public function run(): void
    {
        $locations = [
            [
                'slug' => 'wa_elizabeth_quay',
                'name' => 'Elizabeth Quay',
                'category' => 'scenic',
                'latitude' => -31.9575763,
                'longitude' => 115.85698740000001,
                'address' => 'The Esplanade, Perth WA 6000, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A buzzing riverside precinct of waterfront promenades, bridges and pop-up bars right on the Swan River. The beating heart of modern Perth.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'wa_bell_tower',
                'name' => 'The Bell Tower',
                'category' => 'scenic',
                'latitude' => -31.9590003,
                'longitude' => 115.85829550000001,
                'address' => 'Barrack Square, Riverside Dr, Perth WA 6000, Australia',
                'tier' => 1,
                'is_major_destination' => true,
                'description' => 'A striking copper-and-glass spire on the foreshore housing the historic Swan Bells. Ring a bell, then soak up the river views.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 150,
            ],
            [
                'slug' => 'wa_fremantle_prison',
                'name' => 'Fremantle Prison',
                'category' => 'scenic',
                'latitude' => -32.054983799999995,
                'longitude' => 115.7536591,
                'address' => '1 The Terrace, Fremantle WA 6160, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A World Heritage-listed convict-era gaol with spine-tingling tunnels and torch-lit night tours. History you can almost touch.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'slug' => 'wa_cottesloe_beach',
                'name' => 'Cottesloe Beach',
                'category' => 'scenic',
                'latitude' => -31.993862200000002,
                'longitude' => 115.7510477,
                'address' => 'Cottesloe Beach, Western Australia, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'Perth’s most-loved swimming beach, framed by Norfolk pines and the iconic Indiana teahouse. Golden sand and even better sunsets.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_scarborough_beach',
                'name' => 'Scarborough Beach',
                'category' => 'scenic',
                'latitude' => -31.893518099999998,
                'longitude' => 115.7548947,
                'address' => 'Scarborough Beach, Western Australia, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A lively beachside hub with a buzzing esplanade, surf breaks and an ocean pool. Sun, sand and street-food energy.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_rottnest_island',
                'name' => 'Rottnest Island',
                'category' => 'scenic',
                'latitude' => -31.996502699999997,
                'longitude' => 115.5398997,
                'address' => 'Rottnest Island WA 6161, Australia',
                'tier' => 3,
                'is_major_destination' => true,
                'description' => 'A car-free island paradise of secluded bays, snorkelling reefs and the world-famous selfie-loving quokkas. A true bucket-list escape.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_bibra_lake',
                'name' => 'Bibra Lake',
                'category' => 'parks',
                'latitude' => -32.1071299,
                'longitude' => 115.8072672,
                'address' => 'Bibra Lake WA 6163, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A peaceful wetland reserve with a huge adventure playground, shady picnic spots and walk trails alive with birdlife.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_mandurah_foreshore',
                'name' => 'Mandurah Foreshore',
                'category' => 'scenic',
                'latitude' => -32.5326461,
                'longitude' => 115.7191502,
                'address' => '17 Mandurah Terrace, Mandurah WA 6210, Australia',
                'tier' => 1,
                'is_major_destination' => false,
                'description' => 'A relaxed canal-city waterfront where dolphins cruise the estuary and the boardwalk hums with cafes and street art.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_pinnacles',
                'name' => 'The Pinnacles Desert',
                'category' => 'parks',
                'latitude' => -30.591275000000003,
                'longitude' => 115.1581522,
                'address' => 'Nambung WA 6521, Australia',
                'tier' => 4,
                'is_major_destination' => true,
                'description' => 'Thousands of eerie limestone spires rising from golden desert sands — an otherworldly moonscape that glows at sunrise and sunset.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_lancelin_dunes',
                'name' => 'Lancelin Sand Dunes',
                'category' => 'scenic',
                'latitude' => -31.0020631,
                'longitude' => 115.3307129,
                'address' => 'Beacon Rd, Lancelin WA 6044, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Towering white sand dunes perfect for sandboarding and 4WD adventures, with a sleepy fishing town and turquoise bays nearby.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_kalbarri_natures_window',
                'name' => 'Nature\'s Window',
                'category' => 'parks',
                'latitude' => -27.553136499999997,
                'longitude' => 114.44599269999999,
                'address' => 'Kalbarri National Park WA 6536, Australia',
                'tier' => 4,
                'is_major_destination' => true,
                'description' => 'A natural rock arch perfectly framing the winding Murchison River gorge below. One of WA’s most photographed wonders.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_kalbarri_skywalk',
                'name' => 'Kalbarri Skywalk',
                'category' => 'scenic',
                'latitude' => -27.554840600000002,
                'longitude' => 114.43397089999999,
                'address' => 'West Loop Lookout Road, Kalbarri National Park WA 6536, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'Twin cantilevered platforms jutting out over the Murchison Gorge, leaving you suspended 100 metres above the valley floor.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'wa_geraldton_hmas_sydney',
                'name' => 'HMAS Sydney II Memorial',
                'category' => 'scenic',
                'latitude' => -28.773215,
                'longitude' => 114.6160051,
                'address' => 'Gummer Ave, Geraldton WA 6530, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A moving hilltop memorial of soaring silver gulls honouring the lost crew of HMAS Sydney, with sweeping views over the port city.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'slug' => 'wa_turquoise_bay',
                'name' => 'Turquoise Bay',
                'category' => 'scenic',
                'latitude' => -22.0978565,
                'longitude' => 113.8881097,
                'address' => 'Turquoise Bay, Cape Range National Park WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'A dazzling stretch of white sand where you can snorkel straight off the beach onto the vibrant coral of Ningaloo Reef.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_cape_range_np',
                'name' => 'Cape Range National Park',
                'category' => 'parks',
                'latitude' => -22.236679799999997,
                'longitude' => 113.84652870000001,
                'address' => 'Cape Range National Park WA 6707, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Rugged limestone gorges meet the turquoise Ningaloo coast — home to red kangaroos, deep canyons and reef-fringed beaches.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_exmouth_ningaloo',
                'name' => 'Ningaloo Reef',
                'category' => 'scenic',
                'latitude' => -22.644441399999998,
                'longitude' => 113.6402804,
                'address' => 'Western Australia, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'A pristine fringing reef where you can swim with whale sharks, manta rays and turtles just metres from shore.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_monkey_mia',
                'name' => 'Monkey Mia',
                'category' => 'scenic',
                'latitude' => -25.7953126,
                'longitude' => 113.71665349999999,
                'address' => 'Monkey Mia, WA 6537, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A World Heritage beach famous for its wild bottlenose dolphins that glide into the shallows to greet visitors each morning.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_shell_beach',
                'name' => 'Shell Beach',
                'category' => 'scenic',
                'latitude' => -26.215,
                'longitude' => 113.7736111,
                'address' => 'Shell Beach, Western Australia 6537, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A surreal beach made entirely of billions of tiny white cockle shells, stretching for kilometres along a brilliant blue bay.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_busselton_jetty',
                'name' => 'Busselton Jetty',
                'category' => 'scenic',
                'latitude' => -33.644531199999996,
                'longitude' => 115.34503509999999,
                'address' => '17 Foreshore Parade, Busselton WA 6280, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'The longest timber-piled jetty in the Southern Hemisphere, stretching 1.8km to an underwater observatory amid the coral.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_cape_leeuwin',
                'name' => 'Cape Leeuwin Lighthouse',
                'category' => 'scenic',
                'latitude' => -34.3749541,
                'longitude' => 115.1363477,
                'address' => 'Leeuwin Rd, Augusta WA 6290, Australia',
                'tier' => 4,
                'is_major_destination' => true,
                'description' => 'WA’s tallest lighthouse stands where the Indian and Southern Oceans collide — a dramatic, wind-whipped edge of the continent.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_mammoth_cave',
                'name' => 'Mammoth Cave',
                'category' => 'parks',
                'latitude' => -34.060037,
                'longitude' => 115.02967710000001,
                'address' => 'Caves Rd, Forest Grove WA 6286, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'A vast underground chamber draped in ancient stalactites and fossils, explored on a self-guided boardwalk through the dark.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'slug' => 'wa_margaret_river',
                'name' => 'Margaret River',
                'category' => 'food',
                'latitude' => -33.9535468,
                'longitude' => 115.0629667,
                'address' => 'Margaret River WA 6285, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'The gourmet heart of WA’s wine country, packed with cellar doors, breweries, chocolate factories and farm-gate produce.',
                'image_urls' => ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'wa_the_gap_albany',
                'name' => 'The Gap',
                'category' => 'scenic',
                'latitude' => -35.1184965,
                'longitude' => 117.89235930000001,
                'address' => 'The Gap Rd, Torndirrup WA 6330, Australia',
                'tier' => 4,
                'is_major_destination' => false,
                'description' => 'A sky-bridge platform juts over a churning chasm where the Southern Ocean explodes against towering granite cliffs.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'wa_middleton_beach',
                'name' => 'Middleton Beach',
                'category' => 'scenic',
                'latitude' => -35.022841199999995,
                'longitude' => 117.90885440000001,
                'address' => 'Middleton Beach WA 6330, Australia',
                'tier' => 2,
                'is_major_destination' => false,
                'description' => 'A gorgeous crescent of white sand and calm clear water, with a buzzing boardwalk of cafes right behind the dunes.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_whale_world_albany',
                'name' => 'Albany\'s Historic Whaling Station',
                'category' => 'scenic',
                'latitude' => -35.0952775,
                'longitude' => 117.9594063,
                'address' => '81 Whaling Station Rd, Torndirrup WA 6330, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'The last operating whaling station in the country, now a fascinating museum where you can clamber aboard a real whale chaser.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 250,
            ],
            [
                'slug' => 'wa_lucky_bay',
                'name' => 'Lucky Bay',
                'category' => 'scenic',
                'latitude' => -33.9882318,
                'longitude' => 122.2315877,
                'address' => 'Lucky Bay, Lucky Bay Rd, Cape Le Grand WA 6450, Australia',
                'tier' => 5,
                'is_major_destination' => true,
                'description' => 'Squeaky-white sand, electric-blue water and kangaroos lazing on the beach — routinely voted Australia’s whitest sand.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_cape_le_grand',
                'name' => 'Cape Le Grand National Park',
                'category' => 'parks',
                'latitude' => -33.924932999999996,
                'longitude' => 122.1958746,
                'address' => 'Cape Le Grand Rd, Cape Le Grand WA 6450, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'A coastal wonderland of granite peaks, sweeping bays and turquoise water — hike Frenchman Peak for a jaw-dropping panorama.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_wave_rock',
                'name' => 'Wave Rock',
                'category' => 'scenic',
                'latitude' => -32.441925499999996,
                'longitude' => 118.8970171,
                'address' => '1 Wave Rock Rd, Hyden WA 6359, Australia',
                'tier' => 4,
                'is_major_destination' => true,
                'description' => 'A 15-metre granite wall curled into a perfect breaking wave, streaked with mineral colours and 2.7 billion years old.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 350,
            ],
            [
                'slug' => 'wa_super_pit_lookout',
                'name' => 'KCGM Super Pit Lookout',
                'category' => 'scenic',
                'latitude' => -30.792246399999996,
                'longitude' => 121.50529619999999,
                'address' => 'Mount Monger Rd, Trafalgar WA 6431, Australia',
                'tier' => 3,
                'is_major_destination' => false,
                'description' => 'Peer into one of the largest open-cut gold mines on Earth, where giant haul trucks look like ants on the terraced walls.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 200,
            ],
            [
                'slug' => 'wa_karijini_np',
                'name' => 'Karijini National Park',
                'category' => 'parks',
                'latitude' => -22.6751716,
                'longitude' => 118.2889234,
                'address' => 'Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'A breathtaking maze of deep red gorges, hidden waterfalls and spa-like rock pools carved over billions of years in the Pilbara.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_karijini_fortescue',
                'name' => 'Fortescue Falls',
                'category' => 'parks',
                'latitude' => -22.4777579,
                'longitude' => 118.5506552,
                'address' => 'Dales Rd, Karijini WA 6751, Australia',
                'tier' => 6,
                'is_major_destination' => false,
                'description' => 'A tiered waterfall tumbling into an emerald plunge pool deep within Dales Gorge — a reward at the end of the descent.',
                'image_urls' => ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],
            [
                'slug' => 'wa_cable_beach',
                'name' => 'Cable Beach',
                'category' => 'scenic',
                'latitude' => -17.9319444,
                'longitude' => 122.20805559999998,
                'address' => 'Cable Beach, WA 6726, Australia',
                'tier' => 5,
                'is_major_destination' => true,
                'description' => '22 kilometres of pearl-white sand meeting the Indian Ocean, famous for camel trains silhouetted against fiery tropical sunsets.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 400,
            ],
            [
                'slug' => 'wa_gantheaume_point',
                'name' => 'Gantheaume Point',
                'category' => 'scenic',
                'latitude' => -17.9738748,
                'longitude' => 122.17745679999999,
                'address' => 'Gantheaume Point Rd, Broome WA 6725, Australia',
                'tier' => 5,
                'is_major_destination' => false,
                'description' => 'Fiery red sandstone cliffs plunging into turquoise sea, where 130-million-year-old dinosaur footprints appear at low tide.',
                'image_urls' => ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80', 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80'],
                'geofence_radius_m' => 300,
            ],        ];

        foreach ($locations as $data) {
            // points drives tier via the model's saving() hook; use the per-tier
            // default so the explicit tier and the derived tier agree.
            $data['points'] = Location::defaultPointsForTier($data['tier']);

            Location::updateOrCreate(
                ['slug' => $data['slug']],
                array_merge($data, [
                    'verification_tags' => [],
                    'active' => true,
                    'status' => Location::STATUS_APPROVED,
                    'submitted_by' => null,
                ])
            );
        }
    }
}
